<?php

# Note $this->flashMessenger() refers to a helper that is defined in the Laminas Framework
$flash = $this->flashMessenger();

$flash->setMessageOpenFormat(
    '<div%s>
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
            &times;
        </button>

        <ul class="list-unstyled">
            <li>'
)->setMessageSeparatorString('
            </li>
            <li>')->setMessageCloseString('
            </li>
        </ul>
    </div>');

echo $flash->render('info', ['alert wAlert', 'alert-info', 'alert-dismissable fade show']);
echo $flash->render('error', ['alert wAlert', 'alert-danger', 'alert-dismissable fade show']);
echo $flash->render('warning', ['alert wAlert', 'alert-warning', 'alert-dismissable fade show']);
echo $flash->render('success', ['alert wAlert', 'alert-success', 'alert-dismissable fade show']);
