<?php
$title = $this->translate('Bibliotecas');
$this->headMeta()->appendName('keywords', '');
$this->headMeta()->appendName('description', '');
$this->headTitle($this->escapeHtml($title));
$this->pageBreadcrumbs()->setItems([
    'Home' => $this->url('home'),
    'Bibliotecas' => $this->url('biblioteca'),
]);
// Hoja de estilos requerido
$this->headLink()
    // Css DataTables
    ->prependStylesheet($this->basePath('assets/css/plugins/responsive.bootstrap4.min.css'))
    ->prependStylesheet($this->basePath('assets/css/plugins/dataTables.bootstrap4.min.css'));
$this->inlineScript()
    // Js DataTables
    ->prependFile($this->basePath('assets/js/pages/data-responsive-custom.js'))
    ->prependFile($this->basePath('assets/js/plugins/dataTables.responsive.min.js'))
    ->prependFile($this->basePath('assets/js/plugins/dataTables.bootstrap4.min.js'))
    ->prependFile($this->basePath('assets/js/plugins/jquery.dataTables.min.js'))
    ;
?>
<!-- [ col ] start -->
<div class="col-md-12">
    <div class="card">
        <div class="card-header">
            <h5><?= $title ?></h5>
        </div>
        <div class="card-body">
            <div class="row">
                <div class="col-md-1 col-xs-12 mb-4" align=center>
                    <div class="btn-group" role="group" aria-label="Botones">
                        <a href="<?= $this->url("biblioteca/agregar") ?>" class="btn btn-primary" data-toggle="modal" onClick="add_contribuyente()">Agregar</a>
                        <a href="<?= $this->url("biblioteca/pdf") ?>" class="btn btn-danger">PDF</a>
                        <a href="<?= $this->url("biblioteca/excel") ?>" class="btn btn-success">Excel</a>
                    </div>
                </div>
            </div>
            <table  class="display table table-striped table-hover dt-responsive nowrap" id="bibliotecas" style="width:100%">
                <thead>
                    <tr>
                        <th>ID</th>
                    </tr>
                </thead>
                <tbody>
                    <?php if (!empty($bibliotecas)): ?>
                        <?php foreach ($bibliotecas as $biblioteca): ?>
                            <tr>
                                <td><?= $biblioteca->getIdBiblioteca() ?></td>
                                <td>
                                    <div class="btn-group">
                                        <a href="<?= $this->url('biblioteca/ver', ['action' => 'ver', 'id' => $biblioteca->getIdBiblioteca()]); ?>" class="btn btn-info" data-toggle="modal" onclick="view_contribuyente('<?= $biblioteca->getIdBiblioteca() ?>')"> Ver</a>
                                        <a href="<?= $this->url('biblioteca/editar', ['action' => 'editar', 'id' => $biblioteca->getIdBiblioteca()]); ?>" class="btn btn-warning" data-toggle="modal" onclick="edit_contribuyente('<?= $biblioteca->getIdBiblioteca() ?>')"> Editar</a>
                                        <a href="<?= $this->url('biblioteca/eliminar', ['action' => 'eliminar', 'id' => $biblioteca->getIdBiblioteca()]); ?>" data-toggle="modal" data-target="#deleteModal" data-id="<?= $biblioteca->getIdBiblioteca() ?>" class="btn btn-danger"> Eliminar</a>
                                    </div>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    <?php else: ?>
                        <tr class="text-center">
                            <td colspan="6">No hay datos...</td>
                        </tr>
                    <?php endif; ?>
                </tbody>
            </table>
            <div class="float-right" id="lv-links">
                <?= $this->paginationControl($bibliotecas, 'Sliding', 'catastro/partial/paginator', ['route' => 'bilioteca']); ?>
            </div>
        </div>
    </div>
</div>
<!-- [ col] end -->

<div class="modal fade" id="myModal" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="myModalLabel"></h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <?= $this->form()->openTag($form); ?>
                <input type="hidden" value="" name="id_contribuyente" id="id_contribuyente">
                <div class="form-group">
                    <?= $this->formLabel($form->get('nombre')); ?>
                    <?= $this->formElement($form->get('nombre')); ?>
                    <ul class="text-danger"></ul>
                </div>
                <!-- CSRF -->
                <?= $this->formHidden($form->get('csrf')); ?>
                <ul class="text-danger"></ul>
                <div class="modal-footer">
                <!-- Boton -->
                <?= $this->formSubmit($form->get('btnGuardar')); ?>
                <button id="btnClose" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
                <?= $this->form()->closeTag(); ?>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteModalLabel"></h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>Esta apunto de realizar una accion irreversible hasta para el administrador.</p>
                <p>¿Desea continuar?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger btn-ok">Confirmar</button>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
            </div>
        </div>
    </div>
</div>
