<?php
//    ▄███████▄    ▄████████ ███    █▄     ▄████████ ▀█████████▄     ▄████████
//   ███    ███   ███    ███ ███    ███   ███    ███   ███    ███   ███    ███
//   ███    ███   ███    ███ ███    ███   ███    █▀    ███    ███   ███    ███
//   ███    ███  ▄███▄▄▄▄██▀ ███    ███  ▄███▄▄▄      ▄███▄▄▄██▀    ███    ███
// ▀█████████▀  ▀▀███▀▀▀▀▀   ███    ███ ▀▀███▀▀▀     ▀▀███▀▀▀██▄  ▀███████████
//   ███        ▀███████████ ███    ███   ███    █▄    ███    ██▄   ███    ███
//   ███          ███    ███ ███    ███   ███    ███   ███    ███   ███    ███
//  ▄████▀        ███    ███ ████████▀    ██████████ ▄█████████▀    ███    █▀
//                ███    ███

$title = $this->translate('Test');
$this->headTitle($title);

$this->mainMenu()->setActiveItemId('prueba');

$this->pageBreadcrumbs()->setItems([
'Home'=>$this->url('home'),
'Pruebas'=>$this->url('prueba'),
]);

$form = $this->form;
$form->setAttribute('action', $this->url('prueba/agregar'));
$form->prepare();
?>
<!-- [ col ] start -->
<div class="col-md-12">
<div class="card">
<div class="card-header">
<?php

echo $this->form()->openTag($form);

echo $this->formText($form->get('input1'));
echo $this->formElementErrors($form->get('input1'));

echo $this->formText($form->get('input2'));
echo $this->formElementErrors($form->get('input2'));

echo $this->formSubmit($form->get('btnGuardar'));
echo $this->form()->closeTag();
?>
</div>
<div class="card-body">
</div>
</div>
</div>
<!-- [ col] end -->
