<?php
//    ▄███████▄    ▄████████ ███    █▄     ▄████████ ▀█████████▄     ▄████████
//   ███    ███   ███    ███ ███    ███   ███    ███   ███    ███   ███    ███
//   ███    ███   ███    ███ ███    ███   ███    █▀    ███    ███   ███    ███
//   ███    ███  ▄███▄▄▄▄██▀ ███    ███  ▄███▄▄▄      ▄███▄▄▄██▀    ███    ███
// ▀█████████▀  ▀▀███▀▀▀▀▀   ███    ███ ▀▀███▀▀▀     ▀▀███▀▀▀██▄  ▀███████████
//   ███        ▀███████████ ███    ███   ███    █▄    ███    ██▄   ███    ███
//   ███          ███    ███ ███    ███   ███    ███   ███    ███   ███    ███
//  ▄████▀        ███    ███ ████████▀    ██████████ ▄█████████▀    ███    █▀
//                ███    ███

$title = $this->translate('Test');
$this->headTitle($title);

$this->mainMenu()->setActiveItemId('prueba');

$this->pageBreadcrumbs()->setItems([
'Home'=>$this->url('home'),
'Pruebas'=>$this->url('prueba'),
]);
// Css Requerido
$this->headLink()
    // Css Select2
    ->prependStylesheet($this->basePath('assets/css/plugins/select2.min.css'));
// Js Requerido
$this->inlineScript()
    // Js de la vista
    ->prependFile($this->basePath('js/catastro/prueba/agregar.js'))
    // Js Select2
    ->prependFile($this->basePath('assets/js/plugins/select2.full.min.js'))
    // Js Form validation
    ->prependFile($this->basePath('assets/js/pages/form-validation.js'))
    ->prependFile($this->basePath('assets/js/plugins/jquery.validate.min.js'))
    // Js Bootstrap wizard
    ->prependFile($this->basePath('assets/js/plugins/jquery.bootstrap.wizard.min.js'))
    // Js SweetAlert
    ->prependFile($this->basePath('assets/js/plugins/sweetalert.min.js'))
    ->prependFile($this->basePath('assets/js/pages/ac-alert.js'))
    ;
$form = $this->form;
$form->setAttribute('action', $this->url('prueba/agregar'));
$form->prepare();
?>
<!-- [ col ] start -->
<div class="col-md-12">
<div class="card">
<div class="card-header">
<?php

echo $this->form()->openTag($form);

echo $this->formText($form->get('input1'));
echo $this->formElementErrors($form->get('input1'));

echo $this->formText($form->get('input2'));
echo $this->formElementErrors($form->get('input2'));

echo $this->formSubmit($form->get('btnGuardar'));
echo $this->form()->closeTag();
?>
</div>
<div class="card-body">
</div>
</div>
</div>
<!-- [ col] end -->
