<?php
//    ▄███████▄    ▄████████ ███    █▄     ▄████████ ▀█████████▄     ▄████████
//   ███    ███   ███    ███ ███    ███   ███    ███   ███    ███   ███    ███
//   ███    ███   ███    ███ ███    ███   ███    █▀    ███    ███   ███    ███
//   ███    ███  ▄███▄▄▄▄██▀ ███    ███  ▄███▄▄▄      ▄███▄▄▄██▀    ███    ███
// ▀█████████▀  ▀▀███▀▀▀▀▀   ███    ███ ▀▀███▀▀▀     ▀▀███▀▀▀██▄  ▀███████████
//   ███        ▀███████████ ███    ███   ███    █▄    ███    ██▄   ███    ███
//   ███          ███    ███ ███    ███   ███    ███   ███    ███   ███    ███
//  ▄████▀        ███    ███ ████████▀    ██████████ ▄█████████▀    ███    █▀
//                ███    ███

$title = $this->translate('Test');
$this->headTitle($title);

$this->mainMenu()->setActiveItemId('prueba');

$this->pageBreadcrumbs()->setItems([
'Home'=>$this->url('home'),
'Pruebas'=>$this->url('prueba'),
]);
?>
<!-- [ col ] start -->
<div class="col-md-12">
<div class="card">
<div class="card-header">








</div>
<div class="card-body">
</div>
</div>
</div>
<!-- [ col] end -->
