<?php
//    ▄███████▄    ▄████████ ███    █▄     ▄████████ ▀█████████▄     ▄████████
//   ███    ███   ███    ███ ███    ███   ███    ███   ███    ███   ███    ███
//   ███    ███   ███    ███ ███    ███   ███    █▀    ███    ███   ███    ███
//   ███    ███  ▄███▄▄▄▄██▀ ███    ███  ▄███▄▄▄      ▄███▄▄▄██▀    ███    ███
// ▀█████████▀  ▀▀███▀▀▀▀▀   ███    ███ ▀▀███▀▀▀     ▀▀███▀▀▀██▄  ▀███████████
//   ███        ▀███████████ ███    ███   ███    █▄    ███    ██▄   ███    ███
//   ███          ███    ███ ███    ███   ███    ███   ███    ███   ███    ███
//  ▄████▀        ███    ███ ████████▀    ██████████ ▄█████████▀    ███    █▀
//                ███    ███

$title = $this->translate('Test');
$this->headTitle($title);

$this->mainMenu()->setActiveItemId('prueba');

$this->inlineScript()
    // Js de la vista
    ->prependFile($this->basePath('js/catastro/prueba/index.js'));

$this->pageBreadcrumbs()->setItems([
'Home'=>$this->url('home'),
'Pruebas'=>$this->url('prueba'),
]);
?>
<!-- [ col ] start -->
<div class="col-md-12">
<div class="card">
<div class="card-header">
<a class="btn btn-warning" href="<?=$this->url('prueba/agregar')?>">Agregar un dato de prueba</a>
<hr>
<br>
<?php

if (isset($data->Persona)) {
    if (is_array($data->Persona)) {
        echo $data->Persona[0]->CvePersona;
        // foreach ($data->Persona as $item) {
        //     echo $item->CvePersona;
        //     echo "<br>";
        // }
    }
    echo "<br>";
    echo "seteado";
}

if (isset($data->Predio)) {
    if (is_array($data->Predio)) {
        foreach ($data->Predio as $item) {
            echo $item->PredioId;
            echo "<br>";
        }
    } else {
        echo $data->Predio->PredioId;
        echo "<br>";
    }
    echo "<br>";
    echo "seteado";
}

if (isset($data->PredioColindancia)) {
    if (is_array($data->PredioColindancia)) {
        foreach ($data->PredioColindancia as $item) {
            echo $item->Descripcion;
            echo "<br>";
        }
    } else {
        echo $data->PredioColindancia->Descripcion;
        echo "<br>";
    }
    echo "<br>";
    echo "seteado";
}

echo "<br>";
echo "<hr>";


// if (isset($data->Persona)){

// echo "<pre>";
// print_r($data);
// echo "</pre>";
// }else{
//     echo"NO EXCISTE";
// }

// $cadena = "El 1.05 y el número 20 con menores que el 30";

// $resultado = intval(preg_replace('/[^0-9]+/', '', $cadena), 10);
// echo $resultado; // resultado: 102030
$pago = "$12351172351.35";
if (is_numeric($pago)) {
    echo"es numerico";
}else{

    echo substr($pago,1);
}

    // //Persona físicas
    // $builder = new RfcBuilder();

    // $rfc = $builder->name('Juan José')
    //     ->firstLastName('Cortés')
    //     ->secondLastName('Guzmán')
    //     ->birthday(3, 9, 1984)
    //     ->build()
    //     ->toString();

    // echo $rfc;

    // //Personas morales
    // $builder = new RfcBuilder();

    // $rfc = $builder->legalName('AUTOS PULLMAN, S.A. DE C.V.')
    //     ->creationDate(30, 9, 1964)
    //     ->build()
    //     ->toString();

    // echo $rfc;








?>
</div>
<div class="card-body">
</div>
</div>
</div>
<!-- [ col] end -->
