<?php

namespace DoctrineORMModule\Proxy\__CG__\Catastro\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Predio extends \Catastro\Entity\Predio implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Catastro\\Entity\\Predio' . "\0" . 'idPredio', '' . "\0" . 'Catastro\\Entity\\Predio' . "\0" . 'ubicacion', '' . "\0" . 'Catastro\\Entity\\Predio' . "\0" . 'colonia', '' . "\0" . 'Catastro\\Entity\\Predio' . "\0" . 'localidad', '' . "\0" . 'Catastro\\Entity\\Predio' . "\0" . 'municipio', '' . "\0" . 'Catastro\\Entity\\Predio' . "\0" . 'calle', '' . "\0" . 'Catastro\\Entity\\Predio' . "\0" . 'claveCatastral', '' . "\0" . 'Catastro\\Entity\\Predio' . "\0" . 'cvePredio', '' . "\0" . 'Catastro\\Entity\\Predio' . "\0" . 'numeroExterior', '' . "\0" . 'Catastro\\Entity\\Predio' . "\0" . 'numeroInterior', '' . "\0" . 'Catastro\\Entity\\Predio' . "\0" . 'estatus', '' . "\0" . 'Catastro\\Entity\\Predio' . "\0" . 'tipo', '' . "\0" . 'Catastro\\Entity\\Predio' . "\0" . 'ultimoEjercicioPagado', '' . "\0" . 'Catastro\\Entity\\Predio' . "\0" . 'ultimoPeriodoPagado', '' . "\0" . 'Catastro\\Entity\\Predio' . "\0" . 'titular', '' . "\0" . 'Catastro\\Entity\\Predio' . "\0" . 'titularAnterior', '' . "\0" . 'Catastro\\Entity\\Predio' . "\0" . 'createdAt', '' . "\0" . 'Catastro\\Entity\\Predio' . "\0" . 'updatedAt', '' . "\0" . 'Catastro\\Entity\\Predio' . "\0" . 'idContribuyente'];
        }

        return ['__isInitialized__', '' . "\0" . 'Catastro\\Entity\\Predio' . "\0" . 'idPredio', '' . "\0" . 'Catastro\\Entity\\Predio' . "\0" . 'ubicacion', '' . "\0" . 'Catastro\\Entity\\Predio' . "\0" . 'colonia', '' . "\0" . 'Catastro\\Entity\\Predio' . "\0" . 'localidad', '' . "\0" . 'Catastro\\Entity\\Predio' . "\0" . 'municipio', '' . "\0" . 'Catastro\\Entity\\Predio' . "\0" . 'calle', '' . "\0" . 'Catastro\\Entity\\Predio' . "\0" . 'claveCatastral', '' . "\0" . 'Catastro\\Entity\\Predio' . "\0" . 'cvePredio', '' . "\0" . 'Catastro\\Entity\\Predio' . "\0" . 'numeroExterior', '' . "\0" . 'Catastro\\Entity\\Predio' . "\0" . 'numeroInterior', '' . "\0" . 'Catastro\\Entity\\Predio' . "\0" . 'estatus', '' . "\0" . 'Catastro\\Entity\\Predio' . "\0" . 'tipo', '' . "\0" . 'Catastro\\Entity\\Predio' . "\0" . 'ultimoEjercicioPagado', '' . "\0" . 'Catastro\\Entity\\Predio' . "\0" . 'ultimoPeriodoPagado', '' . "\0" . 'Catastro\\Entity\\Predio' . "\0" . 'titular', '' . "\0" . 'Catastro\\Entity\\Predio' . "\0" . 'titularAnterior', '' . "\0" . 'Catastro\\Entity\\Predio' . "\0" . 'createdAt', '' . "\0" . 'Catastro\\Entity\\Predio' . "\0" . 'updatedAt', '' . "\0" . 'Catastro\\Entity\\Predio' . "\0" . 'idContribuyente'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Predio $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdPredio()
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getIdPredio();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdPredio', []);

        return parent::getIdPredio();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdPredio($idPredio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdPredio', [$idPredio]);

        return parent::setIdPredio($idPredio);
    }

    /**
     * {@inheritDoc}
     */
    public function setUbicacion($ubicacion = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUbicacion', [$ubicacion]);

        return parent::setUbicacion($ubicacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getUbicacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUbicacion', []);

        return parent::getUbicacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setColonia($colonia = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setColonia', [$colonia]);

        return parent::setColonia($colonia);
    }

    /**
     * {@inheritDoc}
     */
    public function getColonia()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getColonia', []);

        return parent::getColonia();
    }

    /**
     * {@inheritDoc}
     */
    public function setLocalidad($localidad = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLocalidad', [$localidad]);

        return parent::setLocalidad($localidad);
    }

    /**
     * {@inheritDoc}
     */
    public function getLocalidad()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLocalidad', []);

        return parent::getLocalidad();
    }

    /**
     * {@inheritDoc}
     */
    public function setMunicipio($municipio = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMunicipio', [$municipio]);

        return parent::setMunicipio($municipio);
    }

    /**
     * {@inheritDoc}
     */
    public function getMunicipio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMunicipio', []);

        return parent::getMunicipio();
    }

    /**
     * {@inheritDoc}
     */
    public function setCalle($calle = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCalle', [$calle]);

        return parent::setCalle($calle);
    }

    /**
     * {@inheritDoc}
     */
    public function getCalle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCalle', []);

        return parent::getCalle();
    }

    /**
     * {@inheritDoc}
     */
    public function setClaveCatastral($claveCatastral = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClaveCatastral', [$claveCatastral]);

        return parent::setClaveCatastral($claveCatastral);
    }

    /**
     * {@inheritDoc}
     */
    public function getClaveCatastral()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClaveCatastral', []);

        return parent::getClaveCatastral();
    }

    /**
     * {@inheritDoc}
     */
    public function setCvePredio($cvePredio = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCvePredio', [$cvePredio]);

        return parent::setCvePredio($cvePredio);
    }

    /**
     * {@inheritDoc}
     */
    public function getCvePredio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCvePredio', []);

        return parent::getCvePredio();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumeroExterior($numeroExterior = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumeroExterior', [$numeroExterior]);

        return parent::setNumeroExterior($numeroExterior);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumeroExterior()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumeroExterior', []);

        return parent::getNumeroExterior();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumeroInterior($numeroInterior = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumeroInterior', [$numeroInterior]);

        return parent::setNumeroInterior($numeroInterior);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumeroInterior()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumeroInterior', []);

        return parent::getNumeroInterior();
    }

    /**
     * {@inheritDoc}
     */
    public function setEstatus($estatus = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEstatus', [$estatus]);

        return parent::setEstatus($estatus);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstatus', []);

        return parent::getEstatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipo($tipo = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipo', [$tipo]);

        return parent::setTipo($tipo);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipo', []);

        return parent::getTipo();
    }

    /**
     * {@inheritDoc}
     */
    public function setUltimoEjercicioPagado($ultimoEjercicioPagado = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUltimoEjercicioPagado', [$ultimoEjercicioPagado]);

        return parent::setUltimoEjercicioPagado($ultimoEjercicioPagado);
    }

    /**
     * {@inheritDoc}
     */
    public function getUltimoEjercicioPagado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUltimoEjercicioPagado', []);

        return parent::getUltimoEjercicioPagado();
    }

    /**
     * {@inheritDoc}
     */
    public function setUltimoPeriodoPagado($ultimoPeriodoPagado = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUltimoPeriodoPagado', [$ultimoPeriodoPagado]);

        return parent::setUltimoPeriodoPagado($ultimoPeriodoPagado);
    }

    /**
     * {@inheritDoc}
     */
    public function getUltimoPeriodoPagado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUltimoPeriodoPagado', []);

        return parent::getUltimoPeriodoPagado();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitular($titular = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitular', [$titular]);

        return parent::setTitular($titular);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitular()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitular', []);

        return parent::getTitular();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitularAnterior($titularAnterior = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitularAnterior', [$titularAnterior]);

        return parent::setTitularAnterior($titularAnterior);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitularAnterior()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitularAnterior', []);

        return parent::getTitularAnterior();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt($createdAt = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', [$createdAt]);

        return parent::setCreatedAt($createdAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', []);

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAt($updatedAt = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAt', [$updatedAt]);

        return parent::setUpdatedAt($updatedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', []);

        return parent::getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdContribuyente(\Catastro\Entity\Contribuyente $idContribuyente = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdContribuyente', [$idContribuyente]);

        return parent::setIdContribuyente($idContribuyente);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdContribuyente()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdContribuyente', []);

        return parent::getIdContribuyente();
    }

}
