
INSERT INTO `localidad` (`id_localidad`, `cve_distrito`, `cve_entidad_federativa`, `cve_localidad`, `cve_municipio`, `cve_region`, `nombre_localidad`, `nombre_oficial_localidad`) VALUES
	(1, 1, 23, 1, 9, 1, 'Tulum                                   ', 'Tulum                                                                                               '),
	(2, 1, 23, 2, 9, 1, 'El Abadejo                              ', 'El Abadejo                                                                                          '),
	(3, 1, 23, 3, 9, 1, 'Águila Azteca                           ', 'Águila Azteca                                                                                       '),
	(4, 1, 23, 5, 9, 1, 'Akumal                                  ', 'Akumal                                                                                              '),
	(5, 1, 23, 6, 9, 1, 'Akumal Beach Resorts                    ', 'Akumal Beach Resorts                                                                                '),
	(6, 1, 23, 7, 9, 1, 'Akumal Sur                              ', 'Akumal Sur                                                                                          '),
	(7, 1, 23, 11, 9, 1, 'Los Arrecifes                           ', 'Los Arrecifes                                                                                       '),
	(8, 1, 23, 12, 9, 1, 'La Ley del Monte                        ', 'La Ley del Monte                                                                                    '),
	(9, 1, 23, 15, 9, 1, 'Ave Fénix                               ', 'Ave Fénix                                                                                           '),
	(10, 1, 23, 16, 9, 1, 'Aventuras Akumal                        ', 'Aventuras Akumal                                                                                    '),
	(11, 1, 23, 18, 9, 1, 'Gran Bahía Príncipe                     ', 'Gran Bahía Príncipe                                                                                 '),
	(12, 1, 23, 21, 9, 1, 'Balam Canché                            ', 'Balam Canché                                                                                        '),
	(13, 1, 23, 24, 9, 1, 'Shamicala Petit                         ', 'Shamicala Petit                                                                                     '),
	(14, 1, 23, 27, 9, 1, 'Boca Paila                              ', 'Boca Paila                                                                                          '),
	(15, 1, 23, 28, 9, 1, 'El Retiro                               ', 'El Retiro                                                                                           '),
	(16, 1, 23, 30, 9, 1, 'Las Cabañas                             ', 'Las Cabañas                                                                                         '),
	(17, 1, 23, 32, 9, 1, 'Cabañas Tulum                           ', 'Cabañas Tulum                                                                                       '),
	(18, 1, 23, 33, 9, 1, 'Caleta Tankah                           ', 'Caleta Tankah                                                                                       '),
	(19, 1, 23, 34, 9, 1, 'SCT [Campamento]                        ', 'SCT [Campamento]                                                                                    '),
	(20, 1, 23, 36, 9, 1, 'Ak\'iin                                  ', 'Ak\'iin                                                                                              '),
	(21, 1, 23, 38, 9, 1, 'Ixchel                                  ', 'Ixchel                                                                                              '),
	(22, 1, 23, 39, 9, 1, 'Casa del Sol                            ', 'Casa del Sol                                                                                        '),
	(23, 1, 23, 44, 9, 1, 'Cayetano Nieto Colín                    ', 'Cayetano Nieto Colín                                                                                '),
	(24, 1, 23, 47, 9, 1, 'Las Chachalacas                         ', 'Las Chachalacas                                                                                     '),
	(25, 1, 23, 51, 9, 1, 'Chanchén Palmar                         ', 'Chanchén Palmar                                                                                     '),
	(26, 1, 23, 52, 9, 1, 'Chanchen Primero                        ', 'Chanchen Primero                                                                                    '),
	(27, 1, 23, 53, 9, 1, 'Chan Chemuyil                           ', 'Chan Chemuyil                                                                                       '),
	(28, 1, 23, 55, 9, 1, 'Ciudad Chemuyil                         ', 'Ciudad Chemuyil                                                                                     '),
	(29, 1, 23, 57, 9, 1, 'Cobá                                    ', 'Cobá                                                                                                '),
	(30, 1, 23, 63, 9, 1, 'Playa Manatí                            ', 'Playa Manatí                                                                                        '),
	(31, 1, 23, 67, 9, 1, 'Crucero de las Ruinas de Tulum          ', 'Crucero de las Ruinas de Tulum                                                                      '),
	(32, 1, 23, 68, 9, 1, 'Bahía Xamach                            ', 'Bahía Xamach                                                                                        '),
	(33, 1, 23, 71, 9, 1, 'Doña Leonor                             ', 'Doña Leonor                                                                                         '),
	(34, 1, 23, 72, 9, 1, 'Dos Ceibas                              ', 'Dos Ceibas                                                                                          '),
	(35, 1, 23, 73, 9, 1, 'Las Dos Hermanas                        ', 'Las Dos Hermanas                                                                                    '),
	(36, 1, 23, 74, 9, 1, 'Dos Ojos                                ', 'Dos Ojos                                                                                            '),
	(37, 1, 23, 76, 9, 1, 'Dos Palmas                              ', 'Dos Palmas                                                                                          '),
	(38, 1, 23, 80, 9, 1, 'Ek Che                                  ', 'Ek Che                                                                                              '),
	(39, 1, 23, 83, 9, 1, 'Esmeralda K                             ', 'Esmeralda K                                                                                         '),
	(40, 1, 23, 85, 9, 1, 'La Esperanza                            ', 'La Esperanza                                                                                        '),
	(41, 1, 23, 92, 9, 1, 'Francisco Uh May                        ', 'Francisco Uh May                                                                                    '),
	(42, 1, 23, 100, 9, 1, 'Hondzonot                               ', 'Hondzonot                                                                                           '),
	(43, 1, 23, 101, 9, 1, 'Houston                                 ', 'Houston                                                                                             '),
	(44, 1, 23, 105, 9, 1, 'El Jaguar                               ', 'El Jaguar                                                                                           '),
	(45, 1, 23, 106, 9, 1, 'Javier Rojo Gómez (Punta Allen)         ', 'Javier Rojo Gómez (Punta Allen)                                                                     '),
	(46, 1, 23, 107, 9, 1, 'Jorge Portilla Manica                   ', 'Jorge Portilla Manica                                                                               '),
	(47, 1, 23, 108, 9, 1, 'Kaape Ha                                ', 'Kaape Ha                                                                                            '),
	(48, 1, 23, 109, 9, 1, 'ZONA COSTERA Y PREDIOS RUSTICOS         ', 'ZONA COSTERA Y PREDIOS RUSTICOS                                                                     '),
	(49, 1, 23, 112, 9, 1, 'Laguna Madera                           ', 'Laguna Madera                                                                                       '),
	(50, 1, 23, 113, 9, 1, 'El Lagunero                             ', 'El Lagunero                                                                                         '),
	(51, 1, 23, 115, 9, 1, 'El Pequeño Paraíso                      ', 'El Pequeño Paraíso                                                                                  '),
	(52, 1, 23, 116, 9, 1, 'Ninguno                                 ', 'Ninguno                                                                                             '),
	(53, 1, 23, 122, 9, 1, 'Mixba                                   ', 'Mixba                                                                                               '),
	(54, 1, 23, 124, 9, 1, 'Lol Beh                                 ', 'Lol Beh                                                                                             '),
	(55, 1, 23, 128, 9, 1, 'Luna                                    ', 'Luna                                                                                                '),
	(56, 1, 23, 133, 9, 1, 'Macario Gómez                           ', 'Macario Gómez                                                                                       '),
	(57, 1, 23, 135, 9, 1, 'El Manatí                               ', 'El Manatí                                                                                           '),
	(58, 1, 23, 136, 9, 1, 'Manuel Antonio Ay                       ', 'Manuel Antonio Ay                                                                                   '),
	(59, 1, 23, 141, 9, 1, 'Maya Tadeo                              ', 'Maya Tadeo                                                                                          '),
	(60, 1, 23, 143, 9, 1, 'Casa Enrique                            ', 'Casa Enrique                                                                                        '),
	(61, 1, 23, 149, 9, 1, 'Azúcar                                  ', 'Azúcar                                                                                              '),
	(62, 1, 23, 150, 9, 1, 'Noh Áaktun                              ', 'Noh Áaktun                                                                                          '),
	(63, 1, 23, 158, 9, 1, 'El Paraíso                              ', 'El Paraíso                                                                                          '),
	(64, 1, 23, 160, 9, 1, 'Paso Juana                              ', 'Paso Juana                                                                                          '),
	(65, 1, 23, 163, 9, 1, 'Pedro Paila                             ', 'Pedro Paila                                                                                         '),
	(66, 1, 23, 166, 9, 1, 'Pesca Maya                              ', 'Pesca Maya                                                                                          '),
	(67, 1, 23, 174, 9, 1, 'Playa Selva                             ', 'Playa Selva                                                                                         '),
	(68, 1, 23, 175, 9, 1, 'Playa Xkanan                            ', 'Playa Xkanan                                                                                        '),
	(69, 1, 23, 176, 9, 1, 'Los Gatos Negros                        ', 'Los Gatos Negros                                                                                    '),
	(70, 1, 23, 184, 9, 1, 'Casa de los Pelícanos                   ', 'Casa de los Pelícanos                                                                               '),
	(71, 1, 23, 185, 9, 1, 'Rancho Alegre                           ', 'Rancho Alegre                                                                                       '),
	(72, 1, 23, 187, 9, 1, 'Jade                                    ', 'Jade                                                                                                '),
	(73, 1, 23, 189, 9, 1, 'Rancho Mariposa                         ', 'Rancho Mariposa                                                                                     '),
	(74, 1, 23, 193, 9, 1, 'Retiro Maya                             ', 'Retiro Maya                                                                                         '),
	(75, 1, 23, 200, 9, 1, 'Sahcab Mucuy                            ', 'Sahcab Mucuy                                                                                        '),
	(76, 1, 23, 201, 9, 1, 'San Agustín                             ', 'San Agustín                                                                                         '),
	(77, 1, 23, 208, 9, 1, 'San Isidro                              ', 'San Isidro                                                                                          '),
	(78, 1, 23, 209, 9, 1, 'San José                                ', 'San José                                                                                            '),
	(79, 1, 23, 210, 9, 1, 'San Juan                                ', 'San Juan                                                                                            '),
	(80, 1, 23, 211, 9, 1, 'San Juan                                ', 'San Juan                                                                                            '),
	(81, 1, 23, 212, 9, 1, 'San Martín                              ', 'San Martín                                                                                          '),
	(82, 1, 23, 218, 9, 1, 'Santa Cruz                              ', 'Santa Cruz                                                                                          '),
	(83, 1, 23, 223, 9, 1, 'Santa Librada                           ', 'Santa Librada                                                                                       '),
	(84, 1, 23, 225, 9, 1, 'Santa Martha Fracción Cinco             ', 'Santa Martha Fracción Cinco                                                                         '),
	(85, 1, 23, 229, 9, 1, 'Santa Teresa                            ', 'Santa Teresa                                                                                        '),
	(86, 1, 23, 234, 9, 1, 'Sol Maya                                ', 'Sol Maya                                                                                            '),
	(87, 1, 23, 236, 9, 1, 'Dreams Tulum                            ', 'Dreams Tulum                                                                                        '),
	(88, 1, 23, 237, 9, 1, 'Tankah Cuatro                           ', 'Tankah Cuatro                                                                                       '),
	(89, 1, 23, 240, 9, 1, 'Tankah Tres                             ', 'Tankah Tres                                                                                         '),
	(90, 1, 23, 241, 9, 1, 'Tankah Uno                              ', 'Tankah Uno                                                                                          '),
	(91, 1, 23, 243, 9, 1, 'La Teresita                             ', 'La Teresita                                                                                         '),
	(92, 1, 23, 244, 9, 1, 'Tita Tulum                              ', 'Tita Tulum                                                                                          '),
	(93, 1, 23, 254, 9, 1, 'El Viejo del Mar                        ', 'El Viejo del Mar                                                                                    '),
	(94, 1, 23, 257, 9, 1, 'Las Villas Akumal                       ', 'Las Villas Akumal                                                                                   '),
	(95, 1, 23, 261, 9, 1, 'La Hamaca Loca                          ', 'La Hamaca Loca                                                                                      '),
	(96, 1, 23, 262, 9, 1, 'Xamach Dos                              ', 'Xamach Dos                                                                                          '),
	(97, 1, 23, 263, 9, 1, 'Xbecal                                  ', 'Xbecal                                                                                              '),
	(98, 1, 23, 264, 9, 1, 'Xcacel                                  ', 'Xcacel                                                                                              '),
	(99, 1, 23, 267, 9, 1, 'Yaxché                                  ', 'Yaxché                                                                                              '),
	(100, 1, 23, 280, 9, 1, 'Casa Godi                               ', 'Casa Godi                                                                                           '),
	(101, 1, 23, 284, 9, 1, 'Casa Tucán                              ', 'Casa Tucán                                                                                          '),
	(102, 1, 23, 288, 9, 1, 'Cenote Kape-Ha                          ', 'Cenote Kape-Ha                                                                                      '),
	(103, 1, 23, 289, 9, 1, 'Chávez Camping                          ', 'Chávez Camping                                                                                      '),
	(104, 1, 23, 291, 9, 1, 'Cibal-Yumtzil                           ', 'Cibal-Yumtzil                                                                                       '),
	(105, 1, 23, 294, 9, 1, 'La Esperanza                            ', 'La Esperanza                                                                                        '),
	(106, 1, 23, 295, 9, 1, 'Estrella, Sol y Luna                    ', 'Estrella, Sol y Luna                                                                                '),
	(107, 1, 23, 297, 9, 1, 'La Guadalupana                          ', 'La Guadalupana                                                                                      '),
	(108, 1, 23, 299, 9, 1, 'Hombre de Piedra                        ', 'Hombre de Piedra                                                                                    '),
	(109, 1, 23, 301, 9, 1, 'Los Jaguares                            ', 'Los Jaguares                                                                                        '),
	(110, 1, 23, 316, 9, 1, 'Pablo Ramos                             ', 'Pablo Ramos                                                                                         '),
	(111, 1, 23, 318, 9, 1, 'Playa Morena de Mar                     ', 'Playa Morena de Mar                                                                                 '),
	(112, 1, 23, 320, 9, 1, 'Rescate Malix                           ', 'Rescate Malix                                                                                       '),
	(113, 1, 23, 322, 9, 1, 'Samasati                                ', 'Samasati                                                                                            '),
	(114, 1, 23, 323, 9, 1, 'San Judas Tadeo                         ', 'San Judas Tadeo                                                                                     '),
	(115, 1, 23, 324, 9, 1, 'Sian Ka\'an Artistas                     ', 'Sian Ka\'an Artistas                                                                                 '),
	(116, 1, 23, 325, 9, 1, 'El Teterete                             ', 'El Teterete                                                                                         '),
	(117, 1, 23, 326, 9, 1, 'La Vía Láctea                           ', 'La Vía Láctea                                                                                       '),
	(118, 1, 23, 327, 9, 1, 'Villa Destini                           ', 'Villa Destini                                                                                       '),
	(119, 1, 23, 330, 9, 1, 'Xi-Cho                                  ', 'Xi-Cho                                                                                              '),
	(120, 1, 23, 334, 9, 1, 'El Álamo                                ', 'El Álamo                                                                                            '),
	(121, 1, 23, 336, 9, 1, 'Alebrijes                               ', 'Alebrijes                                                                                           '),
	(122, 1, 23, 337, 9, 1, 'Aluxes                                  ', 'Aluxes                                                                                              '),
	(123, 1, 23, 338, 9, 1, 'Las Amarantas                           ', 'Las Amarantas                                                                                       '),
	(124, 1, 23, 339, 9, 1, 'Antonio Pool                            ', 'Antonio Pool                                                                                        '),
	(125, 1, 23, 340, 9, 1, 'El Árbol                                ', 'El Árbol                                                                                            '),
	(126, 1, 23, 342, 9, 1, 'Balam Luum                              ', 'Balam Luum                                                                                          '),
	(127, 1, 23, 345, 9, 1, 'Los Capulines                           ', 'Los Capulines                                                                                       '),
	(128, 1, 23, 346, 9, 1, 'La Casa de las Mariposas                ', 'La Casa de las Mariposas                                                                            '),
	(129, 1, 23, 347, 9, 1, 'Casa del Niño                           ', 'Casa del Niño                                                                                       '),
	(130, 1, 23, 351, 9, 1, 'La Ceiba                                ', 'La Ceiba                                                                                            '),
	(131, 1, 23, 353, 9, 1, 'Cenote Calavera                         ', 'Cenote Calavera                                                                                     '),
	(132, 1, 23, 361, 9, 1, 'Colorado                                ', 'Colorado                                                                                            '),
	(133, 1, 23, 363, 9, 1, 'La Consentida                           ', 'La Consentida                                                                                       '),
	(134, 1, 23, 367, 9, 1, 'Los Delfines (Xamach Uno)               ', 'Los Delfines (Xamach Uno)                                                                           '),
	(135, 1, 23, 371, 9, 1, 'Las Dos Luces                           ', 'Las Dos Luces                                                                                       '),
	(136, 1, 23, 372, 9, 1, 'Dos Ojos                                ', 'Dos Ojos                                                                                            '),
	(137, 1, 23, 382, 9, 1, 'La Herencia                             ', 'La Herencia                                                                                         '),
	(138, 1, 23, 383, 9, 1, 'India Blanca                            ', 'India Blanca                                                                                        '),
	(139, 1, 23, 385, 9, 1, 'Kukulkán                                ', 'Kukulkán                                                                                            '),
	(140, 1, 23, 386, 9, 1, 'Le Hoxu\'ul Haltun                       ', 'Le Hoxu\'ul Haltun                                                                                   '),
	(141, 1, 23, 426, 9, 1, 'La Lunita                               ', 'La Lunita                                                                                           '),
	(142, 1, 23, 428, 9, 1, 'El Maguey                               ', 'El Maguey                                                                                           '),
	(143, 1, 23, 429, 9, 1, 'El Manantial                            ', 'El Manantial                                                                                        '),
	(144, 1, 23, 431, 9, 1, 'Maya Art                                ', 'Maya Art                                                                                            '),
	(145, 1, 23, 432, 9, 1, 'Mi Lu\'um                                ', 'Mi Lu\'um                                                                                            '),
	(146, 1, 23, 434, 9, 1, 'Nuevo                                   ', 'Nuevo                                                                                               '),
	(147, 1, 23, 437, 9, 1, 'El Palomar                              ', 'El Palomar                                                                                          '),
	(148, 1, 23, 438, 9, 1, 'Las Palomas                             ', 'Las Palomas                                                                                         '),
	(149, 1, 23, 440, 9, 1, 'Paso Lágrimas                           ', 'Paso Lágrimas                                                                                       '),
	(150, 1, 23, 441, 9, 1, 'El Pedregal                             ', 'El Pedregal                                                                                         '),
	(151, 1, 23, 443, 9, 1, 'Pino Suárez                             ', 'Pino Suárez                                                                                         '),
	(152, 1, 23, 447, 9, 1, 'San Antonio                             ', 'San Antonio                                                                                         '),
	(153, 1, 23, 452, 9, 1, 'San Nazarén                             ', 'San Nazarén                                                                                         '),
	(154, 1, 23, 456, 9, 1, 'Santo Domingo                           ', 'Santo Domingo                                                                                       '),
	(155, 1, 23, 459, 9, 1, 'T. Cañón                                ', 'T. Cañón                                                                                            '),
	(156, 1, 23, 460, 9, 1, 'Tankah Pueblo                           ', 'Tankah Pueblo                                                                                       '),
	(157, 1, 23, 462, 9, 1, 'Tres Hermanos (Emilio)                  ', 'Tres Hermanos (Emilio)                                                                              '),
	(158, 1, 23, 464, 9, 1, 'Tres Vírgenes                           ', 'Tres Vírgenes                                                                                       '),
	(159, 1, 23, 467, 9, 1, 'Vivero Jardín                           ', 'Vivero Jardín                                                                                       '),
	(160, 1, 23, 468, 9, 1, 'Ranitas [Vivero]                        ', 'Ranitas [Vivero]                                                                                    '),
	(161, 1, 23, 470, 9, 1, 'Zhunaan Ha                              ', 'Zhunaan Ha                                                                                          '),
	(162, 1, 23, 901, 9, 1, 'TULUM                                   ', 'TULUM                                                                                               '),
	(163, 1, 23, 902, 9, 1, 'TULUM PUEBLO                            ', 'TULUM PUEBLO                                                                                        '),
	(164, 1, 23, 903, 9, 1, 'TULUM RUINAS                            ', 'TULUM RUINAS                                                                                        '),
	(165, 1, 23, 905, 9, 1, 'AKUMAL                                  ', 'AKUMAL                                                                                              '),
	(166, 1, 23, 906, 9, 1, 'JAVIER ROJO GOMEZ (PUNTA ALLEN)         ', 'JAVIER ROJO GOMEZ (PUNTA ALLEN)                                                                     '),
	(167, 1, 23, 907, 9, 1, 'COBA RUINAS                             ', 'COBA RUINAS                                                                                         '),
	(168, 1, 23, 908, 9, 1, 'YALCHEN                                 ', 'YALCHEN                                                                                             '),
	(169, 1, 23, 909, 9, 1, 'CHANCHEN                                ', 'CHANCHEN                                                                                            '),
	(170, 1, 23, 910, 9, 1, 'SACAMUCUY                               ', 'SACAMUCUY                                                                                           '),
	(171, 1, 23, 911, 9, 1, 'YAXCHE                                  ', 'YAXCHE                                                                                              '),
	(172, 1, 23, 912, 9, 1, 'SAN PEDRO                               ', 'SAN PEDRO                                                                                           '),
	(173, 1, 23, 913, 9, 1, 'SAN SILVERIO                            ', 'SAN SILVERIO                                                                                        '),
	(174, 1, 23, 914, 9, 1, 'CHEMUYIL                                ', 'CHEMUYIL                                                                                            '),
	(175, 1, 23, 916, 9, 1, 'JACINTO PAT                             ', 'JACINTO PAT                                                                                         '),
	(176, 1, 23, 917, 9, 1, 'MACARIO GOMEZ                           ', 'MACARIO GOMEZ                                                                                       '),
	(177, 1, 23, 918, 9, 1, 'MANUEL ANTONIO AY                       ', 'MANUEL ANTONIO AY                                                                                   '),
	(178, 1, 23, 919, 9, 1, 'FRANCISCO UH MAY                        ', 'FRANCISCO UH MAY                                                                                    '),
	(179, 1, 23, 920, 9, 1, 'SAN JUAN                                ', 'SAN JUAN                                                                                            '),
	(180, 1, 23, 921, 9, 1, 'ZONA COSTERA                            ', 'ZONA COSTERA                                                                                        ');

