<?php
$title = $this->translate('Agregar predio');
$this->headMeta()->appendName('keywords', '');
$this->headMeta()->appendName('description', '');
$this->headTitle($this->escapeHtml($title));
$this->pageBreadcrumbs()->setItems([
    'Home' => $this->url('home'),
    'Predios' => $this->url('predio'),
    'Agregar' => $this->url('predio/agregar'),
]);
// Css Requerido
$this->headLink()
    // Css Select2
    ->prependStylesheet($this->basePath('assets/css/plugins/select2.min.css'));
// Js Requerido
$this ->inlineScript()
    // Js de la vista
    ->prependFile($this->basePath('js/catastro/predio/add.js'))
    // Js Select2
    ->prependFile($this->basePath('assets/js/plugins/select2.full.min.js'));
// Instancia del form
$form = $this->form;
$form->setAttribute('action', $this->url('predio/agregar'));
$form->prepare();
?>
<!-- [ col ] start -->
<div class="col">
    <div class="card">
        <div class="card-header text-center">
            <h5>Alta Predio</h5>
        </div>
        <!-- [ card-body ] start -->
        <div class="card-body">
            <?= $this->form()->openTag($form); ?>
                <div class="form-row">
                    <div class="form-group">
                        <?= $this->formSelect($form->get('cve_catastral')->setAttributes(['class' => "custom-select js-select2-predio col-sm-12"])); ?>
                        <div class="text-danger">
                            <?= $this->formElementErrors($form->get('cve_catastral')); ?>
                        </div>
                    </div>
                </div>
                <hr>
                <div class="form-row">
                    <div class="form-group col">
                        <?= $this->formLabel($form->get('ultimo_ejercicio_pagado')); ?>
                        <?= $this->formText($form->get('ultimo_ejercicio_pagado')); ?>
                        <div class="text-danger">
                            <?= $this->formElementErrors($form->get('ultimo_ejercicio_pagado')); ?>
                        </div>
                    </div>
                    <div class="form-group col">
                        <?= $this->formLabel($form->get('ultimo_periodo_pagado')); ?>
                        <?= $this->formText($form->get('ultimo_periodo_pagado')); ?>
                        <div class="text-danger">
                            <?= $this->formElementErrors($form->get('ultimo_periodo_pagado')); ?>
                        </div>
                    </div>
                </div>
                <h6 class="text-center">Ubicación Geográfica</h6>
                <hr>
                <div class="form-row">
                    <div class="form-group col">
                        <?= $this->formLabel($form->get('municipio')); ?>
                        <?= $this->formText($form->get('municipio')); ?>
                        <div class="text-danger">
                            <?= $this->formElementErrors($form->get('municipio')); ?>
                        </div>
                    </div>
                    <div class="form-group col">
                        <?= $this->formLabel($form->get('localidad')); ?>
                        <?= $this->formText($form->get('localidad')); ?>
                        <div class="text-danger">
                            <?= $this->formElementErrors($form->get('localidad')); ?>
                        </div>
                    </div>
                    <div class="form-group col">
                        <?= $this->formLabel($form->get('colonia')); ?>
                        <?= $this->formText($form->get('colonia')); ?>
                        <div class="text-danger">
                            <?= $this->formElementErrors($form->get('colonia')); ?>
                        </div>
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col">
                        <?= $this->formLabel($form->get('calle')); ?>
                        <?= $this->formText($form->get('calle')); ?>
                        <div class="text-danger">
                            <?= $this->formElementErrors($form->get('calle')); ?>
                        </div>
                    </div>
                    <div class="form-group col">
                        <?= $this->formLabel($form->get('numero_exterior')); ?>
                        <?= $this->formText($form->get('numero_exterior')); ?>
                        <div class="text-danger">
                            <?= $this->formElementErrors($form->get('numero_exterior')); ?>
                        </div>
                    </div>
                    <div class="form-group col">
                        <?= $this->formLabel($form->get('numero_interior')); ?>
                        <?= $this->formText($form->get('numero_interior')); ?>
                        <div class="text-danger">
                            <?= $this->formElementErrors($form->get('numero_interior')); ?>
                        </div>
                    </div>
                </div>
                <h6 class="text-center">Datos de propietario</h6>
                <hr>
                <div class="form-row">
                    <?= $this->formText($form->get('input1')); ?>
                    <div class="form-group col">
                        <?= $this->formLabel($form->get('titular')); ?>
                        <?= $this->formText($form->get('titular')); ?>
                        <div class="text-danger">
                            <?= $this->formElementErrors($form->get('titular')); ?>
                        </div>
                    </div>
                    <div class="form-group col">
                        <?= $this->formLabel($form->get('titular_anterior')); ?>
                        <?= $this->formText($form->get('titular_anterior')); ?>
                        <div class="text-danger">
                            <?= $this->formElementErrors($form->get('titular_anterior')); ?>
                        </div>
                    </div>
                </div>
                <h6 class="text-center">Colindancias del predio</h6>
                <hr>
                <div class="row">
                    <div class="col">
                        <button type="button" class="btn btn-success btn-sm float-right mb-2" data-toggle="modal" data-target="#AgregarColindanciaModal"><i class="fas fa-plus fa-fw"></i></button>
                    </div>
                </div>
                <table  id="mytable" class="table table-bordered table-hover ">
                  <tr>
                    <th>Punto cardinal</th>
                    <th>Colinda con</th>
                    <th>Metros</th>
                    <th>Observaciones</th>
                    <th>Eliminar</th>
                  </tr>
                </table>
                <p class="text-right">Elementos en la Tabla: <span id="adicionados">0</span></p>
                
                <!-- Modal -->
                <div class="modal fade" id="AgregarColindanciaModal" tabindex="-1" role="dialog" aria-labelledby="AgregarColindanciaModalLabel" aria-hidden="true">
                  <div class="modal-dialog" role="document">
                    <div class="modal-content">
                      <div class="modal-header">
                        <h5 class="modal-title" id="AgregarColindanciaModalLabel">Agregar colindancia </h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                          <span aria-hidden="true">&times;</span>
                        </button>
                      </div>
                      <div class="modal-body">
                            <div class="form-row">
                                <div class="form-group col">
                                    <label for="puntoCardinal">Punto cardinal: </label>
                                    <select class="custom-select w-30" name="puntoCardinal" id="puntoCardinal">
                                        <option name="Norte">Norte</option>
                                        <option name="Sur">Sur</option>
                                        <option name="Este">Este</option>
                                        <option name="Oeste">Oeste</option>
                                    </select>
                                </div>
                                <div class="form-group col">
                                    <label for="colindaCon">Colinda con: </label>
                                    <input class="form-control" type="text" name="colindaCon" id="colindaCon" placeholder="Colindancia">
                                </div>
                                <div class="form-group col">
                                    <label for="medidasMetro">Medidda metros: </label>
                                    <input class="form-control" type="text" name="medidasMetro" id="medidasMetro" placeholder="Metros" onkeypress="return filterFloat(event,this);">
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="form-group col">
                                    <label for="">Observaciones: </label>
                                    <textarea class="form-control" name="observacionesColindancias" id="observacionesColindancias" placeholder="Observaciones" rows="3"></textarea>
                                </div>
                            </div>
                      </div>
                      <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
                        <button type="button" class="btn btn-success" id="adicionar">Adicionar a la tabla</button>
                      </div>
                    </div>
                  </div>
                </div>
                <h6 class="text-center"><?= $this->formLabel($form->get('archivo')); ?></h6>
                <hr>
                <div class="form-group" id="select">
                    <div class="input-group mb-3">
                        <div class="input-group-append delete">
                            <span class="input-group-text" title="Remove this field"><i class="fas fa-times"></i></span>
                        </div>
                            <?= $this->formSelect($form->get('id_archivo_categoria')->setName("id_archivo_categoria[]")->setValueOptions($this->categorias)); ?>
                        <div class="custom-file">
                            <?= $this->formFile($form->get('archivo')); ?>
                            <div class="text-danger">
                                <?= $this->formElementErrors($form->get('id_archivo_categoria')); ?>
                                <?= $this->formElementErrors($form->get('archivo')); ?>
                            </div>
                        </div>
                    </div>
                </div>

                <div id="additionalselects">
                </div>

                <div class="btn-group float-right">
                    <?= $this->formButton($form->get('add_more')); ?>
                </div>
                <?= $this->formHidden($form->get('csrf')); ?>
                <div class="text-danger">
                    <?= $this->formElementErrors($form->get('csrf')); ?>
                </div>
                <?= $this->formSubmit($form->get('btnGuardar')); ?>
                <a href="<?= $this->url("predio") ?>" class="btn btn-secondary"> Volver atrás</a>
            <?= $this->form()->closeTag(); ?>
        </div>
        <!-- [ card-body ] end -->
    </div>
</div>
<!-- [ col ] end -->
