<?php
$title = $this->translate('Predios');
$this->headMeta()->appendName('keywords', '');
$this->headMeta()->appendName('description', '');
$this->headTitle($this->escapeHtml($title));
$this->pageBreadcrumbs()->setItems([
    'Home' => $this->url('home'),
    'Predios' => $this->url('predio'),
]);
// Css Requerido
$this->headLink()
    // Css DataTables
    ->prependStylesheet($this->basePath('assets/css/plugins/responsive.bootstrap4.min.css'))
    ->prependStylesheet($this->basePath('assets/css/plugins/dataTables.bootstrap4.min.css'));
$this->inlineScript()
    // Js de la vista
    ->prependFile($this->basePath('js/catastro/predio/index.js'))
    // Js DataTables
    ->prependFile($this->basePath('assets/js/plugins/dataTables.responsive.min.js'))
    ->prependFile($this->basePath('assets/js/plugins/dataTables.bootstrap4.min.js'))
    ->prependFile($this->basePath('assets/js/plugins/jquery.dataTables.min.js'))
    ;
?>
<!-- [ col ] start -->
<div class="col-md-12">
    <div class="card">
        <div class="card-header">
            <h5><?= $title ?></h5>
        </div>
        <div class="card-body">
            <div class="row">
                <div class="col-md-1 col-xs-12 mb-4" align=center>
                    <div class="btn-group" role="group" aria-label="Botones">
                        <a href="<?= $this->url("predio/agregar") ?>" class="btn btn-primary" >Agregar</a>
                    </div>
                </div>
            </div>
            <table  class='display table table-striped table-hover dt-responsive nowrap' id="predios" style="width:100%">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Clave Catastral</th>
                        <th>Contribuyente</th>
                        <th>Titular</th>
                        <th>Ubicacion</th>
                        <th>Opciones</th>
                    </tr>
                </thead>
                <tbody>
                    <?php if (!empty($predios)): ?>
                        <?php foreach ($predios as $predio): ?>
                            <tr>
                                <td><?= $predio->getIdPredio() ?></td>
                                <td><?= $predio->getClaveCatastral() ?></td>
                                <!-- TODO: Consultar desde el Webservice antes te mostrarlo en la tabla de predios -->
                                <td><?php echo $predio->getIdContribuyente()->getNombre()?></td>
                                <td><?php echo $predio->getTitular()?></td>
                                <td><?= $predio->getLocalidad() ?></td>
                                <td>
                                    <div class="btn-group">
                                        <a href="<?= $this->url('predio/ver', ['action' => 'ver', 'id' => $predio->getIdPredio()]); ?>" class="btn btn-info"> Detalle</a>
                                    </div>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    <?php else: ?>
                        <tr class="text-center">
                            <td colspan="6">No hay datos...</td>
                        </tr>
                    <?php endif; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>
<!-- [ col] end -->
