<?php
$title = $this->translate('Detalle');
$this->headMeta()->appendName('keywords', '');
$this->headMeta()->appendName('description', '');
$this->headTitle($this->escapeHtml($title));
$this->pageBreadcrumbs()->setItems([
    'Home' => $this->url('home'),
    'Predio' => $this->url('predio'),
    'Detalle' => $this->url('predio/ver'),
]);
// Css Requerido
$this->headLink()
    // Css FileInput
    ->prependStylesheet($this->basePath('js/plugins/FileInput/css/fileinput.min.css'))
    ;
// Js Requerido
$this ->inlineScript()
    // Js de la vista
    ->prependFile($this->basePath('js/catastro/predio/view.js'))
    // Js FileInput
    ->prependFile($this->basePath('js/plugins/FileInput/js/locales/es.js'))
    ->prependFile($this->basePath('js/plugins/FileInput/js/fileinput.min.js'))
    ;
?>
<!-- [ col ] start -->
<div class="col-md-6">
    <div class="card">
        <div class="card-header">
            <h5>Predio</h5>
        </div>
        <div class="card-body">
            <table class="table table-striped table-bordered">
                <tbody>
                    <tr>
                        <td>Clave Catastral</td>
                        <td><?= $predio->getClaveCatastral() ?></td>
                    </tr>
                    <tr>
                        <td>Ubicación</td>
                        <td><?= $predio->getUbicacion() ?></td>
                    </tr>
                    <tr>
                        <td>Colonia</td>
                        <td><?= $predio->getColonia() ?></td>
                    </tr>
                    <tr>
                        <td>Localidad</td>
                        <td><?= $predio->getLocalidad() ?></td>
                    </tr>
                    </tr>
                    <tr>
                        <td>Municipio</td>
                        <td><?= $predio->getMunicipio() ?></td>
                    </tr>
                    </tr>
                    <tr>
                        <td>Calle</td>
                        <td><?= $predio->getCalle() ?></td>
                    </tr>
                    <tr>
                        <td>Numero Exterior</td>
                        <td><?= $predio->getNumeroExterior() ?></td>
                    </tr>
                    <tr>
                        <td>Numero Interior</td>
                        <td><?= $predio->getNumeroInterior() ?></td>
                    </tr>
                </tbody>
            </table>
            <a href="<?= $this->url('predio') ?>" class="btn btn-secondary">Volver al listado</a>
        </div>
    </div>
</div>
<!-- [ col] end -->
<!-- [ col ] start -->
<div class="col-md-6">
    <div class="card">
        <div class="card-header">
            <h5>Colindancias</h5>
        </div>
        <div class="card-body">
            <table class="table table-striped table-bordered">
                <tbody>
                    <?php if ($colindancias): ?>
                        <?php
                            foreach ($colindancias as $r) {
                                $medidas[] = $r->getMedidaMetros();
                                $descripcion[] = $r->getDescripcion();
                            }
                        ?>
                        <tr>
                            <td>Al Norte</td>
                            <td><?= $medidas[0] ?></td>
                            <td>Colinda con</td>
                            <td><?= $descripcion[0] ?></td>
                        </tr>
                        <tr>
                            <td>Al Sur</td>
                            <td><?= $medidas[1] ?></td>
                            <td>Colinda con</td>
                            <td><?= $descripcion[1] ?></td>
                        </tr>
                        <tr>
                            <td>Al Este</td>
                            <td><?= $medidas[2] ?></td>
                            <td>Colinda con</td>
                            <td><?= $descripcion[2] ?></td>
                        </tr>
                        <tr>
                            <td>Al Oeste</td>
                            <td><?= $medidas[3] ?></td>
                            <td>Colinda con</td>
                            <td><?= $descripcion[3] ?></td>
                        </tr>
                    <?php else: ?>
                        <tr>
                            <td colspan="4" class="text-center">No hay colindancias...</td>
                        </tr>
                    <?php endif; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>
<!-- [ col] end -->
<!-- [ col ] start -->
<div class="col-md-12">
    <div class="card">
        <div class="card-header">
            <h5>Archivos</h5>
            <div class="float-right">
                <button id="agregar-archivo" class="btn btn-success btn-sm" data-toggle="modal" data-target="#subirArchivoModal">Agregar+</button>
            </div>
        </div>
        <div class="card-body">
            <table class="table table-light" id="archivosList">
                <thead class="thead-dark">
                    <tr>
                        <th>Tipo</th>
                        <th>Archivo</th>
                        <th>Fecha de subida</th>
                        <th>Acciones</th>
                    </tr>
                </thead>
                <tbody>
                    <?php if ($archivos): ?>
                        <?php foreach ($archivos as $archivo): ?>
                            <tr>
                                <td><?= $archivo->getIdArchivo()->getIdArchivoCategoria()->getNombre() ?></td>
                                <td><?= $archivo->getIdArchivo()->getUrl() ?></td>
                                <td><?= $archivo->getIdArchivo()->getCreatedAt()->format('Y-m-d h:m:s') ?></td>
                                <td>
                                    <a target="_blank" href="<?= $this->url('biblioteca/ver-archivo', ['archivo'=>'file'], ['query'=>['name'=>$archivo->getIdArchivo()->getUrl()]]); ?>"  class="btn btn-info btn-sm" role="button"> Previsualizar</a>
                                    <a href="<?= $this->url('biblioteca/descargar-archivo', ['action' => 'descargar-archivo', 'archivo' => $archivo->getIdArchivo()->getIdArchivo()]); ?>" class="btn btn-success btn-sm"> Descargar</a>
                                    <a href="<?= $this->url('biblioteca/eliminar-archivo-predio', ['action' => 'eliminar-archivo-predio', 'predio' => $archivo->getIdPredio()->getIdPredio(), 'archivo' => $archivo->getIdArchivo()->getIdArchivo()]); ?>" class="btn btn-danger btn-sm"> Eliminar</a>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    <?php else: ?>
                        <tr>
                            <td colspan="4" class="text-center">No hay archivos...</td>
                        </tr>
                    <?php endif; ?>
                </tbody>
            </table>

        </div>
    </div>
</div>
<!-- [ col] end -->
<!-- Modal -->
<div class="modal fade" id="subirArchivoModal" tabindex="-1" role="dialog" aria-labelledby="subirArchivoLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
    <div class="modal-content">
        <div class="modal-header">
        <h5 class="modal-title" id="subirArchivoLabel">Cargar archivo...</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        </div>
        <div class="modal-body">
            <form action="#" method="post" enctype="multipart/form-data" id="subirArchivoForm">
                <div class="form-group">
                    <input type="hidden" name="input1" value="<?= $predioId ?>">
                </div>
                <div class="form-group">
                    <select class="form-control" id="id_archivo_categoria" name="id_archivo_categoria">
                        <?php foreach($categorias as $categoria): ?>
                            <?= '<option value="'. $categoria->getIdArchivoCategoria() .'">' . $categoria->getNombre() . '</option>'?>
                        <?php endforeach;?>
                    </select>
                </div>
                <div class="form-group">
                    <div class="file-loading">
                        <input type="file" name="archivo" id="archivo">
                    </div>
                </div>
            </form>
        </div>
        <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
        </div>
    </div>
    </div>
</div>
<!-- [ col] end -->
