<!DOCTYPE html>
<html lang="en">
<head>
    <title>Gradient Able bootstrap admin template by codedthemes</title>
    <!-- HTML5 Shim and Respond.js IE11 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 11]>
    	<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    	<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    	<![endif]-->
    <!-- Meta -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="description" content="" />
    <meta name="keywords" content="">
    <meta name="author" content="Codedthemes" />
    <!-- Favicon icon -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/assets/images/favicon.ico'])
            ->prependStylesheet($this->basePath('assets/css/style.css'))
        ?>
</head>
<!-- [ offline-ui ] start -->
<div class="auth-wrapper offline">
    <div class="offline-wrapper">
        <img src=<?= $this->basePath('assets/images/maintance/sparcle-1.png') ?> alt="User-Image" class="img-fluid s-img-1">
        <img src=<?= $this->basePath('assets/images/maintance/sparcle-2.png') ?> alt="User-Image" class="img-fluid s-img-2">
        <div class="container off-main">
            <div class="row justify-content-center">
                <div class="col-6">
                    <div class="text-center">
                        <div class="moon"></div>
                        <img src=<?= $this->basePath('assets/images/maintance/ship.svg') ?> alt="" class="img-fluid boat-img">
                    </div>
                </div>
            </div>
            <div class="row m-0 justify-content-center off-content">
                <div class="col-sm-12 p-0">
                    <div class="text-center">
                        <h1 class="text-white text-uppercase">Offline</h1>
                        <h5 class="text-white font-weight-normal m-b-30">The site is temporarily down</h5>
                        <button class="btn btn-primary mb-4"><i class="feather icon-refresh-ccw mr-2"></i>Reload</button>
                        <h2><?= $this->message ?></h2>

                        <?php if (isset($this->display_exceptions) && $this->display_exceptions): ?>

                        <?php if(isset($this->exception) && ($this->exception instanceof Exception || $this->exception instanceof Error)): ?>
                        <hr/>
                        <h2>Additional information:</h2>
                        <h3><?= get_class($this->exception) ?></h3>
                        <dl>
                            <dt>File:</dt>
                            <dd>
                                <pre class="prettyprint linenums"><?= $this->exception->getFile() ?>:<?= $this->exception->getLine() ?></pre>
                            </dd>
                            <dt>Message:</dt>
                            <dd>
                                <pre class="prettyprint linenums"><?= $this->escapeHtml($this->exception->getMessage()) ?></pre>
                            </dd>
                            <dt>Stack trace:</dt>
                            <dd>
                                <pre class="prettyprint linenums"><?= $this->escapeHtml($this->exception->getTraceAsString()) ?></pre>
                            </dd>
                        </dl>
                        <?php
                            $e = $this->exception->getPrevious();
                            $icount = 0;
                            if ($e) :
                        ?>
                        <hr/>
                        <h2>Previous exceptions:</h2>
                        <ul class="unstyled">
                            <?php while($e) : ?>
                            <li>
                                <h3><?= get_class($e) ?></h3>
                                <dl>
                                    <dt>File:</dt>
                                    <dd>
                                        <pre class="prettyprint linenums"><?= $e->getFile() ?>:<?= $e->getLine() ?></pre>
                                    </dd>
                                    <dt>Message:</dt>
                                    <dd>
                                        <pre class="prettyprint linenums"><?= $this->escapeHtml($e->getMessage()) ?></pre>
                                    </dd>
                                    <dt>Stack trace:</dt>
                                    <dd>
                                        <pre class="prettyprint linenums"><?= $this->escapeHtml($e->getTraceAsString()) ?></pre>
                                    </dd>
                                </dl>
                            </li>
                            <?php
                                $e = $e->getPrevious();
                                $icount += 1;
                                if ($icount >= 50) {
                                    echo "<li>There may be more exceptions, but we have no enough memory to proccess it.</li>";
                                    break;
                                }
                                endwhile;
                            ?>
                        </ul>
                        <?php endif; ?>

                        <?php else: ?>

                        <h3>No Exception available</h3>

                        <?php endif ?>

                        <?php endif ?>
                    </div>
                </div>
                <div class="sark">
                    <img src=<?= $this->basePath('assets/images/maintance/sark.svg') ?> alt="" class="img-fluid img-sark">
                    <div class="bubble"></div>
                </div>
            </div>
        </div>
        <svg width="100%" height="70%" version="1.1" xmlns="http://www.w3.org/2000/svg" class="wave">
            <title>Wave</title>
            <defs></defs>
            <path id="feel-the-wave" d="" />
        </svg>
        <svg width="100%" height="70%" version="1.1" xmlns="http://www.w3.org/2000/svg" class="wave">
            <title>Wave</title>
            <defs></defs>
            <path id="feel-the-wave-two" d="" />
        </svg>
    </div>
</div>
<!-- [ offline-ui ] end -->
<!-- Required Js -->
<?= $this->inlineScript()
    ->prependFile($this->basePath('assets/js/pages/jquery.wavify.js'))
    ->prependFile($this->basePath('assets/js/pages/TweenMax.min.js'))
    ->prependFile($this->basePath('assets/js/plugins/bootstrap.min.js'))
    ->prependFile($this->basePath('assets/js/vendor-all.min.js'))
?>

<script>
    $('#feel-the-wave').wavify({
        color: 'rgba(37, 54, 83, 0.93)',
        speed: .25
    });
    $('#feel-the-wave-two').wavify({
        color: 'rgba(37, 54, 83, .5)',
        speed: .35
    });
</script>
</body>
</html>
