<?php
$title = $this->translate('Edit User');

$this->headMeta()->appendName('keywords', '');

$this->headMeta()->appendName('description', '');

$this->headTitle($this->escapeHtml($title));

$this->mainMenu()->setActiveItemId('roles');

$this->pageBreadcrumbs()->setItems([
    'Home'=>$this->url('home'),
    'Manage Users'=>$this->url('users'),
    'Edit User'=>$this->url('users', ['action'=>'edit', 'id'=>$user->getId()])
]);

$form->get('email')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'name@example.com'
    ]);

$form->get('full_name')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'John Doe'
    ]);

$form->get('status')->setAttributes([
    'class'=>'form-control'
    ]);

$form->get('roles')->setAttributes([
    'class'=>'form-control'
    ]);

$form->get('submit')
        ->setAttributes(['class'=>'btn btn-primary'])
        ->setValue('Save');

$form->prepare();
?>
<!-- [ col ] start -->
<div class="col-md-6">
    <div class="card">
        <div class="card-header">
            <h5><?= $title ?></h5>
        </div>
        <div class="card-body">
            <h1>Edit User <?= $this->escapeHtml($user->getEmail()) ?></h1>
            <!-- [ openTag ] start -->
            <?= $this->form()->openTag($form); ?>
                <div class="form-group">
                    <?= $this->formLabel($form->get('email')); ?>
                    <?= $this->formElement($form->get('email')); ?>
                    <?= $this->formElementErrors($form->get('email')); ?>
                </div>

                <div class="form-group">
                    <?= $this->formLabel($form->get('full_name')); ?>
                    <?= $this->formElement($form->get('full_name')); ?>
                    <?= $this->formElementErrors($form->get('full_name')); ?>
                </div>

                <div class="form-group">
                    <?= $this->formLabel($form->get('status')); ?>
                    <?= $this->formElement($form->get('status')); ?>
                    <?= $this->formElementErrors($form->get('status')); ?>
                </div>

                <div class="form-group">
                    <?= $this->formLabel($form->get('roles')); ?>
                    <?= $this->formElement($form->get('roles')); ?>
                    <?= $this->formElementErrors($form->get('roles')); ?>
                </div>

                <?= $this->formElement($form->get('csrf')); ?>
                <?= $this->formElementErrors($form->get('csrf')); ?>
                <?= $this->formElement($form->get('submit')); ?>
            <?= $this->form()->closeTag(); ?>
            <!-- [ closeTag ] start -->
        </div>
    </div>
</div>
<!-- [ col] end -->
