<?php
$title = $this->translate('Roles');

$this->headMeta()->appendName('keywords', '');

$this->headMeta()->appendName('description', '');

$this->headTitle($this->escapeHtml($title));

$this->mainMenu()->setActiveItemId('users');

$this->pageBreadcrumbs()->setItems([
    'Home'=>$this->url('home'),
    'Manage Users'=>$this->url('users'),
]);
?>
<!-- [ col ] start -->
<div class="col-md-12">
    <div class="card">
        <div class="card-header">
            <h1>Manage Users</h1>
        </div>
        <div class="card-body">
            <div class="row">
                <div class="col-md-1 col-xs-12 mb-4" align=center>
                    <a class="btn btn-primary" href="<?= $this->url('users', ['action'=>'add']); ?>"> New User</a>
                </div>
            </div>
            <table class="table table-light">
                <thead class="thead-light">
                    <tr>
                        <th>ID</th>
                        <th>E-mail</th>
                        <th>Full Name</th>
                        <th>Role(s)</th>
                        <th>Date Created</th>
                        <th>Status</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($users as $user): ?>
                        <tr>
                            <td><?= $this->escapeHtml($user->getId()); ?></td>
                            <td>
                                <a href="<?= $this->url('users', ['action'=>'view', 'id'=>$user->getId()]); ?>">
                                    <?= $this->escapeHtml($user->getEmail()); ?>
                                </a>
                            </td>
                            <td>
                                <?= $this->escapeHtml($user->getFullName()); ?></a>
                            </td>
                            <td>
                                <?= $this->escapeHtml($user->getRolesAsString()); ?></a>
                            </td>
                            <td><nobr><?= $this->escapeHtml($user->getDateCreated()); ?></nobr></td>
                            <td>
                                <?= $this->escapeHtml($user->getStatusAsString()); ?>
                            </td>
                            <td>
                                <a class="btn btn-info" href="<?= $this->url('users', ['action'=>'edit', 'id'=>$user->getId()]); ?>"> Edit</a>
                                <a class="btn btn-secondary" href="<?= $this->url('users', ['action'=>'change-password', 'id'=>$user->getId()]); ?>"> Change Password</a>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
            <?= $this->paginationControl($users,
                                'Sliding',
                                'user/partial/paginator',
                                array('route' => 'users')); ?>
        </div>
    </div>
</div>
<!-- [ col] end -->
