<?php
$title = $this->translate('View User');

$this->headMeta()->appendName('keywords', '');

$this->headMeta()->appendName('description', '');

$this->headTitle($this->escapeHtml($title));

$this->mainMenu()->setActiveItemId('users');

$this->pageBreadcrumbs()->setItems([
    'Home'=>$this->url('home'),
    'Manage Users'=>$this->url('users'),
    'View User'=>$this->url('users', ['action'=>'view', 'id'=>$user->getId()])
]);
?>
<!-- [ col ] start -->
<div class="col-md-6">
    <div class="card">
        <div class="card-header">
            <h5><?= $title ?></h5>
        </div>
        <div class="card-body">
        <h1>View User <?= $this->escapeHtml($user->getEmail()) ?></h1>
            <table class="table table-striped table-bordered">
                <tr>
                    <th>ID:</th>
                    <td><?= $this->escapeHtml($user->getId()) ?></th>
                </tr>
                <tr>
                    <th>E-mail:</th>
                    <td><?= $this->escapeHtml($user->getEmail()) ?></th>
                </tr>
                <tr>
                    <th>Full Name:</th>
                    <td><?= $this->escapeHtml($user->getFullName()) ?></th>
                </tr>
                <tr>
                    <th>Date Created:</th>
                    <td><?= $this->escapeHtml($user->getDateCreated()) ?></th>
                </tr>
                <tr>
                    <th>Status:</th>
                    <td><?= $this->escapeHtml($user->getStatusAsString()) ?></th>
                </tr>
                <tr>
                    <th>Roles:</th>
                    <td><?= $this->escapeHtml($user->getRolesAsString()) ?></th>
                </tr>
            </table>
            <div>
                <a class="btn btn-info" href="<?= $this->url('users', ['action'=>'edit', 'id'=>$user->getId()]); ?>"> Edit</a>
                <a class="btn btn-secondary" href="<?= $this->url('users', ['action'=>'change-password', 'id'=>$user->getId()]); ?>"> Change Password</a>
            </div>
        </div>
    </div>
</div>
<!-- [ col] end -->
