<?php
$title = 'Bienvenido';
$this->headTitle($title);

$this->mainMenu()->setActiveItemId('home');

$this->pageBreadcrumbs()->setItems([
            'Home'=>$this->url('home')
            ]);
?>
<!-- [ col ] start -->
<div class="col-md-12">
    <div class="card">
        <div class="card-header">
            Cabecera.
        </div>
        <div class="card-body">
            <h5 class="card-title">Titulo</h5>
            <p class="card-text">Contenido.</p>
        </div>
        <div class="card-footer">
            Pie de página.
        </div>
    </div>
</div>
<!-- [ col] end -->





