<?php
$title = $this->translate('Agregar');
$this->headMeta()->appendName('keywords', '');
$this->headMeta()->appendName('description', '');
$this->headTitle($this->escapeHtml($title));
$this->pageBreadcrumbs()->setItems([
    'Home' => $this->url('home'),
    'Aportaciones' => $this->url('aportacion'),
    'Agregar' => $this->url('aportacion/nueva-aportacion'),
]);
// Css Requerido
$this->headLink()
    // Css Select2
    ->prependStylesheet($this->basePath('assets/css/plugins/select2.min.css'));
// Js Requerido
$this->inlineScript()
    // Js de la vista
    ->prependFile($this->basePath('js/catastro/aportacion/add.js'))
    // Js Select2
    ->prependFile($this->basePath('assets/js/plugins/select2.full.min.js'))
    // Js Form validation
    ->prependFile($this->basePath('assets/js/pages/form-validation.js'))
    ->prependFile($this->basePath('assets/js/plugins/jquery.validate.min.js'))
    // Js Bootstrap wizard
    ->prependFile($this->basePath('assets/js/plugins/jquery.bootstrap.wizard.min.js'))
    // Js SweetAlert
    ->prependFile($this->basePath('assets/js/plugins/sweetalert.min.js'))
    ->prependFile($this->basePath('assets/js/pages/ac-alert.js'))
    ;
$form = $this->form;
$form->setAttribute('action', $this->url('aportacion/nueva-aportacion'));
$form->prepare();
?>
<div class="col-md-12">
    <div class="card">
        <div class="card-header">
            <h5>Aportacion</h5>
        </div>
        <div class="card-body">
            <div class="bt-wizard" id="besicwizard">
                <ul class="nav nav-pills nav-fill mb-3">
                    <!-- <li class="nav-item"><a href="#b-w-tab1" class="nav-link" data-toggle="tab">Requerimientos</a></li> -->
                    <li class="nav-item"><a href="#b-w-tab2" class="nav-link" data-toggle="tab">Datos</a></li>
                    <li class="nav-item"><a href="#b-w-tab3" class="nav-link" data-toggle="tab">Calculo de pago</a></li>
                    <!-- <li class="nav-item"><a href="#b-w-tab4" class="nav-link" data-toggle="tab">Final</a></li> -->
                </ul>
                <?= $this->form()->openTag($form);?>
                <div class="tab-content">
                <div class="tab-pane active show" id="b-w-tab1">
            <!--Inicio Tab 1  -->
                <h1 class="text-center bg-secondary">Requisitos</h1><br>
                <div class="to-do-list mb-3 none">
                    <div class="d-inline-block">
                        <label class="check-task custom-control custom-checkbox d-flex justify-content-center">
                            <input type="checkbox" class="custom-control-input" id="val1"  onchange="javascript:showContent()" >
                            <span class="custom-control-label">Documentos que acredite la propiedad</span>
                        </label>
                    </div>
                    <div class="float-right"><a onclick="delete_todo(8);" href="#!" class="delete_todolist"><i class="far fa-trash-alt"></i></a></div>
                    </div>

                    <div class="to-do-list mb-3">
                    <div class="d-inline-block">
                        <label class="check-task custom-control custom-checkbox d-flex justify-content-center">
                            <input type="checkbox" class="custom-control-input" id="val2" onchange="javascript:showContent()" >
                            <span class="custom-control-label">Carta Poder Notariada o Simple (En caso de ser simple debera ser acompañada con la firma e indentificacion de 2 testigos)</span>
                        </label>
                    </div>
                    <div class="float-right"><a onclick="delete_todo(9);" href="#!" class="delete_todolist"><i class="far fa-trash-alt"></i></a></div>
                </div>

                <div class="to-do-list mb-3">
                    <div class="d-inline-block">
                        <label class="check-task custom-control custom-checkbox d-flex justify-content-center">
                            <input type="checkbox" class="custom-control-input" id="val3"   onchange="javascript:showContent()" >
                            <span class="custom-control-label">Ine del Propietario (Arrendador/Arrendatario)</span>
                        </label>
                    </div>
                    <div class="float-right"><a onclick="delete_todo(10);" href="#!" class="delete_todolist"><i class="far fa-trash-alt"></i></a></div>
                </div>

                <div class="to-do-list mb-3">
                    <div class="d-inline-block">
                        <label class="check-task custom-control custom-checkbox d-flex justify-content-center">
                            <input type="checkbox" class="custom-control-input" id="val4"   onchange="javascript:showContent()" >
                            <span class="custom-control-label">Plano topografico con cordenadas UTM (Impresa o Digital)</span>
                        </label>
                    </div>
                    <div class="float-right"><a onclick="delete_todo(11);" href="#!" class="delete_todolist"><i class="far fa-trash-alt"></i></a></div>
                </div>


                <div class="to-do-list mb-3">
                    <div class="d-inline-block">
                        <label class="check-task custom-control custom-checkbox d-flex justify-content-center">
                            <input type="checkbox" class="custom-control-input" id="val5"  onchange="javascript:showContent()" >
                            <span class="custom-control-label">Ultimo pago Realizado</span>
                        </label>
                    </div>
                    <div class="float-right"><a onclick="delete_todo(12);" href="#!" class="delete_todolist"><i class="far fa-trash-alt"></i></a></div>
                </div>

                <div class="to-do-list mb-3">
                    <div class="d-inline-block">
                        <label class="check-task custom-control custom-checkbox d-flex justify-content-center">
                            <input type="checkbox" class="custom-control-input" id="val6"   onchange="javascript:showContent()" >
                            <span class="custom-control-label">Foto del Predio</span>
                        </label>
                    </div>
                    <div class="float-right"><a onclick="delete_todo(13);" href="#!" class="delete_todolist"><i class="far fa-trash-alt"></i></a></div>
                </div>

                    <div class="to-do-list mb-3">
                    <div class="d-inline-block">
                        <label class="check-task custom-control custom-checkbox d-flex justify-content-center">
                            <input type="checkbox" class="custom-control-input" id="val7" onchange="javascript:showContent()" >
                            <span class="custom-control-label">Escrito,(Nombre Completo, Numero Telefonico)</span>
                        </label>
                    </div>
                    <div class="float-right"><a onclick="delete_todo(14);" href="#!" class="delete_todolist"><i class="far fa-trash-alt"></i></a></div>
                </div>


            <!-- Fin Tab 1 -->
                    </div>
                    <div class="tab-pane" id="b-w-tab2">
                    <h3 class="text-center bg-secondary">TARGETA DE APORTACION</h3>
                        <div class="row ml-0  ">
                        <div class="col-sm-6">
                        <div class="form-group">
                        <!-- Select Contirbuyente Id -->
                            <?= $this->formLabel($form->get('contribuyente_id')); ?>
                            <?= $this->formSelect($form->get('contribuyente_id')->setAttributes(['class' => "custom-select js-data-example-ajax2 col"]));?>
                            <div class="text-danger">
                                <?= $this->formElementErrors($form->get('contribuyente_id')); ?>
                            </div>
                        </div>
                    </div>
                            <div class="col-sm-3">
                                <div class="form-group ">
                                <!-- Input Categoria-->
                                    <?= $this->formLabel($form->get('categoria')); ?>
                                    <?= $this->formText($form->get('categoria')); ?>
                                    <div class="text-danger">
                                        <?= $this->formElementErrors($form->get('categoria')); ?>
                                    </div>
                                </div>
                            </div>
                            <div class="col-sm-3">
                                <div class="form-group ">
                                <!-- Input Condicion-->
                                    <?= $this->formLabel($form->get('condicion')); ?>
                                    <?= $this->formText($form->get('condicion')); ?>
                                    <div class="text-danger">
                                        <?= $this->formElementErrors($form->get('condicion')); ?>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <h3 class="text-center bg-secondary">DATOS DEL POSECIONARIO</h3>
                        <div class="row ml-0">
                            <div class="col-sm-4">
                                <div class="form-group ">
                                <!-- Input Titular-->
                                <?= $this->formLabel($form->get('titular')); ?>
                                    <?= $this->formText($form->get('titular')); ?>
                                    <div class="text-danger">
                                        <?= $this->formElementErrors($form->get('titular')); ?>
                                    </div>
                                </div>
                            </div>
                            <div class="col-sm-4">
                                <div class="form-group ">
                                <!-- Input Ubicacion-->
                                    <?= $this->formLabel($form->get('ubicacion')); ?>
                                    <?= $this->formText($form->get('ubicacion')); ?>
                                    <div class="text-danger">
                                        <?= $this->formElementErrors($form->get('ubicacion')); ?>
                                    </div>
                                </div>
                            </div>
                            <div class="col-sm-4">
                                <div class="form-group ">
                                <!-- Input Localidad-->
                                    <?= $this->formLabel($form->get('localidad')); ?>
                                    <?= $this->formText($form->get('localidad')); ?>
                                    <div class="text-danger">
                                        <?= $this->formElementErrors($form->get('localidad')); ?>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row ml-0 ">
                        <div class="col-sm-4 ">
                            <div class="form-group ">
                            <!-- Input Documentos de propiedad-->
                                <?= $this->formLabel($form->get('d_propiedad')); ?>
                                <?= $this->formText($form->get('d_propiedad')); ?>
                                <div class="text-danger">
                                    <?= $this->formElementErrors($form->get('d_propiedad')); ?>
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-1">
                        <div class="form-group ">
                        <!-- Input Norte-->
                                <?= $this->formLabel($form->get('norte')); ?>
                                <?= $this->formText($form->get('norte')); ?>
                                <div class="text-danger">
                                    <?= $this->formElementErrors($form->get('norte')); ?>
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-3">
                        <div class="form-group ">
                        <!-- Input Con Norte-->
                                <?= $this->formLabel($form->get('con_norte')); ?>
                                <?= $this->formText($form->get('con_norte')); ?>
                                <div class="text-danger">
                                    <?= $this->formElementErrors($form->get('con_norte')); ?>
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-1">
                        <div class="form-group ">
                        <!-- Input Sur-->
                                <?= $this->formLabel($form->get('sur')); ?>
                                <?= $this->formText($form->get('sur')); ?>
                                <div class="text-danger">
                                    <?= $this->formElementErrors($form->get('sur')); ?>
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-3">
                        <div class="form-group ">
                        <!-- Input Con sur-->
                                <?= $this->formLabel($form->get('con_sur')); ?>
                                <?= $this->formText($form->get('con_sur')); ?>
                                <div class="text-danger">
                                    <?= $this->formElementErrors($form->get('con_sur')); ?>
                                </div>
                            </div>
                        </div>
                        </div>
                        <div class="row ml-0">
                        <div class="col-sm-4">
                            <div class="form-group ">
                            <!-- Input Arrendador-->
                                <?= $this->formLabel($form->get('arrendador')); ?>
                                <?= $this->formText($form->get('arrendador')); ?>
                                <div class="text-danger">
                                    <?= $this->formElementErrors($form->get('arrendador')); ?>
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-1">
                        <div class="form-group ">
                        <!-- Input Este-->
                                <?= $this->formLabel($form->get('este')); ?>
                                <?= $this->formText($form->get('este')); ?>
                                <div class="text-danger">
                                    <?= $this->formElementErrors($form->get('este')); ?>
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-3">
                        <div class="form-group ">
                        <!-- Input Con este-->
                                <?= $this->formLabel($form->get('con_este')); ?>
                                <?= $this->formText($form->get('con_este')); ?>
                                <div class="text-danger">
                                    <?= $this->formElementErrors($form->get('con_este')); ?>
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-1">
                        <div class="form-group ">
                        <!-- Input Oeste-->
                                <?= $this->formLabel($form->get('oeste')); ?>
                                <?= $this->formText($form->get('oeste')); ?>
                                <div class="text-danger">
                                    <?= $this->formElementErrors($form->get('oeste')); ?>
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-3">
                        <div class="form-group ">
                        <!-- Input Con este-->
                                <?= $this->formLabel($form->get('con_oeste')); ?>
                                <?= $this->formText($form->get('con_oeste')); ?>
                                <div class="text-danger">
                                    <?= $this->formElementErrors($form->get('con_oeste')); ?>
                                </div>
                            </div>
                        </div>
                        </div>
                        <div class="row ml-0">
                            <div class="col-sm-4">
                            <div class="form-group ">
                            <!-- Input Documentos de arrendamiento-->
                                <?= $this->formLabel($form->get('d_arrendamiento')); ?>
                                <?= $this->formText($form->get('d_arrendamiento')); ?>
                                <div class="text-danger">
                                    <?= $this->formElementErrors($form->get('d_arrendamiento')); ?>
                                </div>
                            </div>
                            </div>
                            <div class="col-sm-4">
                            <div class="form-group ">
                            <!-- Input Fecha Adquicision-->
                                    <?= $this->formLabel($form->get('fecha_adquisicion')); ?>
                                    <?= $this->formDate($form->get('fecha_adquisicion')) ?>
                                    <div class="text-danger">
                                        <?= $this->formElementErrors($form->get('fecha_adquisicion')); ?>
                                    </div>
                                </div>
                            </div>
                            <div class="col-sm-4">
                                <div class="form-group ">
                                <!-- Input Titulo anterior-->
                                    <?= $this->formLabel($form->get('titular_anterior')); ?>
                                    <?= $this->formText($form->get('titular_anterior')); ?>
                                    <div class="text-danger">
                                        <?= $this->formElementErrors($form->get('titular_anterior')); ?>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <h3 class="text-center bg-secondary">DATOS DEL INMUEBLE</h3>
                        <div class="row ml-0">
                            <div class="col-sm-6">
                                <div class="form-group ">
                                <!-- Input Giro Comercial-->
                                    <?= $this->formLabel($form->get('g_comercial')); ?>
                                    <?= $this->formText($form->get('g_comercial')); ?>
                                    <div class="text-danger">
                                        <?= $this->formElementErrors($form->get('g_comercial')); ?>
                                    </div>
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <div class="form-group ">
                                <!-- Input -Nombre comercial-->
                                    <?= $this->formLabel($form->get('n_comercial')); ?>
                                    <?= $this->formText($form->get('n_comercial')); ?>
                                    <div class="text-danger">
                                        <?= $this->formElementErrors($form->get('n_comercial')); ?>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row ml-0">
                            <div class="col-sm-6">
                                <div class="form-group ">
                                <!-- Input Superficie Ocupada-->
                                    <?= $this->formLabel($form->get('s_ocupada')); ?>
                                    <?= $this->formText($form->get('s_ocupada')); ?>
                                    <div class="text-danger">
                                        <?= $this->formElementErrors($form->get('s_ocupada')); ?>
                                    </div>
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <div class="form-group ">
                                <!-- Input Uso destino -->
                                    <?= $this->formLabel($form->get('u_destino')); ?>
                                    <?= $this->formText($form->get('u_destino')); ?>
                                    <div class="text-danger">
                                        <?= $this->formElementErrors($form->get('u_destino')); ?>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="tab-pane" id="b-w-tab3">
                    <!-- Inicio Del Calculo de pago -->
                    <h3 class="text-center bg-secondary">DATOS  DE POSSESION</h3>
                        <div class="row ml-0">
                            <div class="col-sm-2">
                                <div class="form-group ">
                                <!-- Input Sup. M2 Terreno -->
                                    <?= $this->formLabel($form->get('terreno')); ?>
                                    <?= $this->formText($form->get('terreno')); ?>
                                    <div class="text-danger">
                                        <?= $this->formElementErrors($form->get('terreno')); ?>
                                    </div>
                                </div>
                            </div>
                            <div class="col-sm-2">
                                <div class="form-group ">
                                <!-- Input Valor del Terreno -->
                                    <?= $this->formLabel($form->get('v_terreno')); ?>
                                    <?= $this->formText($form->get('v_terreno')); ?>
                                    <div class="text-danger">
                                        <?= $this->formElementErrors($form->get('v_terreno')); ?>
                                    </div>
                                    </div>
                            </div>
                            <div class="col-sm-2">
                                <div class="form-group ">
                                <!-- Input Sup.M2 Construcion -->
                                    <?= $this->formLabel($form->get('sup_m')); ?>
                                    <?= $this->formText($form->get('sup_m')); ?>
                                    <div class="text-danger">
                                        <?= $this->formElementErrors($form->get('sup_m')); ?>
                                    </div>
                                </div>
                            </div>
                            <div class="col-sm-2">
                                <div class="form-group">
                                <!-- Select Valores de Construccion -->
                                    <label class="form-label">Valores de Construccion</label>
                                    <select class=" js-example-basic-single2" name="validation-select" id="valor_c" onchange="valorC()">
                                            <option value="0">Buscar...</option>
                                            <?php if ($valorConstruccions): ?>
                                            <?php foreach ($valorConstruccions as $valorConstruccion):?>
                                            <optgroup label=<?= $valorConstruccion->getGrupo()?>>
                                            <option value="<?= $valorConstruccion->getCosto()?>"><?= $valorConstruccion->getCaracteristicas() ?></option>
                                        </optgroup>
                                        <?php endforeach; ?>
                                        <?php endif; ?>
                                    </select>
                                </div>
                            </div>
                            <div class="col-sm-2">
                                <div class="form-group ">
                                <!--Input Valor de la construccion-->
                                    <?= $this->formLabel($form->get('v_c')); ?>
                                    <?= $this->formText($form->get('v_c')); ?>
                                    <div class="text-danger">
                                        <?= $this->formElementErrors($form->get('v_c')); ?>
                                    </div>
                                </div>
                            </div>
                            <div class="col-sm-2">
                                <div class="form-group ">
                                <!--Input Avaluo Total -->
                                    <?= $this->formLabel($form->get('a_total')); ?>
                                    <?= $this->formText($form->get('a_total')); ?>
                                    <div class="text-danger">
                                        <?= $this->formElementErrors($form->get('a_total')); ?>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row ml-0">
                            <div class="col-sm-3">
                                <div class="form-group ">
                                <!-- Input Vigencia -->
                                    <?= $this->formLabel($form->get('vig')); ?>
                                    <?= $this->formDate($form->get('vig')) ?>
                                    <div class="text-danger">
                                        <?= $this->formElementErrors($form->get('vig')); ?>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-3">
                                <div class="form-group">
                                <!-- Select Tasa Impositiva -->
                                    <label class="form-label">Tasa Impositiva</label>
                                    <select class="form-control" name="tasa_i" id="tasa_i" onchange="timpositiva()">
                                        <option value="0">Selecione uno..</option>
                                        <optgroup label="Predios Urbanos Edificados">
                                            <option value="0.0017">0.0017</option>
                                        </optgroup>
                                        <optgroup label="Predios Urbanos Edificados">
                                            <option value="0.0050">0.0050</option>
                                        </optgroup>
                                        <optgroup label="Tulum">
                                            <option value="0.0050">0.0050</option>
                                        </optgroup>
                                        <optgroup label="Otras Zonas Urbanas">
                                            <option value="0.00567">0.00567</option>
                                        </optgroup>
                                        <optgroup label="Predio Rusticos">
                                            <option value="0.00380">0.00380</option>
                                        </optgroup>
                                    </select>
                                </div>
                            </div>
                            <div class="col-sm-3">
                                <div class="form-group ">
                                <!-- Input Ejercicio Fiscal -->
                                    <?= $this->formLabel($form->get('ejercicio_f')); ?>
                                    <?= $this->formText($form->get('ejercicio_f')); ?>
                                    <div class="text-danger">
                                        <?= $this->formElementErrors($form->get('ejercicio_f')); ?>
                                    </div>
                                </div>
                            </div>
                            <!-- Input Oculto para hacer el calculo -->
                            <input type="hidden" id="v_in">
                            <div class="col-sm-3">
                                <div class="form-group ">
                                <!--Input Pago aportacion-->
                                    <?= $this->formLabel($form->get('pago_a'));?>
                                    <?= $this->formText($form->get('pago_a'));?>
                                    <div class="text-danger">
                                        <?= $this->formElementErrors($form->get('pago_a')); ?>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- Input Oculto para validar validacion vacia-->
                        <input type="hidden" id=p_hide>

                        <div class="row ml-0">
                            <div class="col-sm-4">
                            <!-- Input Estatus Oculto -->
                                <?= $this->formText($form->get('status')); ?>
                                <div class="text-danger">
                                    <?= $this->formElementErrors($form->get('status')); ?>
                                </div>
                            </div>
                            <div class="col-sm-4">
                            <!-- Input cvpredio Oculto -->
                                <?= $this->formText($form->get('cvepredio')); ?>
                                <div class="text-danger">
                                    <?= $this->formElementErrors($form->get('cvepredio')); ?>
                                </div>
                            </div>
                            <div class="col-sm-4">
                                <div class="form-group ">
                                <!-- Input Id oculto -->
                                    <?= $this->formText($form->get('parametro')->setValue($id)); ?>
                                    <div class="text-danger">
                                        <?= $this->formElementErrors($form->get('parametro')); ?>
                                    </div>
                                </div>
                            </div>
                            <?= $this->formHidden($form->get('csrf')); ?>
                            <div class="text-danger">
                                <?= $this->formElementErrors($form->get('csrf')); ?>
                            </div>
                            <div class="col-sm-12 text-md-right mb-3">
                            <!-- Buton Guardar -->
                            <!-- <?php // echo $this->formSubmit($form->get('btnGuardar')->setAttributes(['onclick' => "confirmReset()"]));?> -->
                            <?= $this->formSubmit($form->get('btnGuardar')); ?>
                            </div>
                        </div>
                    <?= $this->form()->closeTag(); ?>
                    </div>
                    <div class="tab-pane" id="b-w-tab4">
                        <form class="text-center">
                            <i class="feather icon-check-circle display-3 text-success"></i>
                            <h5 class="mt-3">Registration Done! . .</h5>
                            <p>Lorem Ipsum is simply dummy text of the printing</p>
                            <div class="custom-control custom-checkbox mb-3">
                                <input type="checkbox" class="custom-control-input" id="customCheck2">
                                <label class="custom-control-label" for="customCheck2">Subscribe Newslatter</label>
                            </div>
                        </form>
                    </div>
                    <div class="row justify-content-between btn-page">
                        <div class="col-sm-6">
                            <a href="#!" class="btn btn-primary button-previous">Previous</a>
                        </div>
                        <div class="col-sm-6 text-md-right">
                            <a href="#!" class="btn btn-primary button-next">Next</a>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>




