<!-- Modal -->
    <div class="modal fade" id="addContribuyente" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Agregar Contribuyente</h5>
            <input id="hdn_id_cont" class="form-control" type="hidden"  name="">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">
            <div class="row ml-0">
                <div class="col-sm-4">
                    <div class="form-group ">
                        <label >Tipo de Contribuyente</label>
                        <select class="custom-select w-30" name="" id="tipoContribuyente" onchange="tipoPersona()">
                        <option value="F">Fisica</option>
                        <option value="M">Moral</option>
                        </select>
                    </div>
                </div>
            </div>
            <hr>
            <div class="row ml-0">
                <div id="div_nombre" class="col-sm-4">
                    <div class="form-group">
                    <label >Nombre</label>
                    <input class="form-control" type="text" name="" id="nombreContribuyente" placeholder="Nombre">
                    </div>
                </div>
                <div id="div_apellidoPaterno" class="col-sm-4">
                    <div class="form-group">
                    <label>Apellido Paterno</label>
                    <input class="form-control" type="text" name="" id="apellidoPaterno"  placeholder="Apellido Paterno" >
                    </div>
                </div>
                <div id="div_apellidoMaterno" class="col-sm-4">
                    <div class="form-group ">
                    <label >Apellido Materno</label>
                    <input class="form-control" type="text" name="" id="apellidoMaterno"  placeholder="Apellido Materno">
                    </div>
                </div>
            </div>
            <div class="row ml-0">
                <div id="div_rfc" class="col-sm-4">
                    <div class="form-group">
                    <label>R.F.C.</label>
                    <input class="form-control" type="text" name="" id="rfc" placeholder="R.F.C">
                    </div>
                </div>
                <div id="div_razonSocial" class="col-sm-4">
                    <div class="form-group">
                    <label>Razón Social</label>
                    <input class="form-control" type="text" name=""  id="razonSocial" placeholder="Razón Social">
                    </div>
                </div>
                <div id="div_curp" class="col-sm-4">
                    <div class="form-group">
                    <label>C.U.R.P.</label>
                    <input class="form-control" type="text" name="" id="curp" placeholder="C.U.R.P">
                    </div>
                </div>
                <div id="div_estadoCivil" class="col-sm-4">
                    <div class="form-group ">
                        <label >Estado Civil</label>
                        <select class="custom-select w-30" name="" id="estadoCivil">
                        <option value="S">Soltero</option>
                        <option value="C">Casado</option>
                        </select>
                    </div>
                </div>
            </div>
            <div class="row ml-0">
                <div id="div_fechaNacimeinto" class="col-sm-4">
                    <div class="form-group">
                    <font size="1"><label>Fecha de nacimiento</label></font>
                        <select class="custom-select w-30" name="" id="dia" >
                            <option value="">Día</option>
                            <?php for ($i=1; $i < 32 ; $i++) { ?>
                                <option value="<?=$i?>"><?=$i?></option>
                            <?php } ?>
                        </select>
                    </div>
                </div>
                <div id="div_mes" class="col-sm-4">
                    <div class="form-group">
                    <br id="br_mes">
                        <select class="custom-select w-30" name="" id="mes">
                            <option value="">Mes</option>
                            <option value="1">Enero</option>
                            <option value="2">Febrero</option>
                            <option value="3">Marzo</option>
                            <option value="4">Abril</option>
                            <option value="5">Mayo</option>
                            <option value="6">Junio</option>
                            <option value="7">Julio</option>
                            <option value="8">Agosto</option>
                            <option value="9">Septiembre</option>
                            <option value="10">Octubre</option>
                            <option value="12">Noviembre</option>
                            <option value="12">Diciembre</option>
                        </select>
                    </div>
                </div>
                <div id="div_año" class="col-sm-4">
                    <div class="form-group">
                        <br id="br_año">
                        <select class="custom-select w-30" name="" id="año">
                            <option value="">Año</option>
                            <?php for ($i=2008; $i > 1921 ; $i--) { ?>
                                <option value="<?=$i?>"><?=$i?></option>
                            <?php } ?>
                        </select>
                    </div>
                </div>
            </div>
            <div class="row ml-0">
                <div  id="div_correoElectronico" class="col-sm-4">
                    <div class="form-group ">
                    <font size="1"><label>Correo Electrónico</label></font>
                    <input class="form-control" type="text" name="" id="correoElectronico"  placeholder="Correo Electrónico">
                    </div>
                </div>
                <div id="div_telefono" class="col-sm-4">
                    <div  class="form-group ">
                    <label>Telefono</label>
                    <input class="form-control" type="text" name="" id="telefono" onkeypress="return validaNumericos(event);" placeholder="Telefono">
                    </div>
                </div>
                <div id="div_genero" class="col-sm-4">
                    <div class="form-group ">
                    <label>Genero</label>
                    <select class="custom-select w-30" name="" id="genero">
                            <option value="M">Masculino</option>
                            <option value="F">Femenino</option>
                            <option value="O">Otros</option>
                    </select>
                    </div>
                </div>
            </div>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
            <button type="button" class="btn btn-primary" id="btn_guardar">Guardar Cambios</button>
        </div>
        </div>
    </div>
</div>

