<?php
$title = $this->translate('Aportaciones');
$this->headMeta()->appendName('keywords', '');
$this->headMeta()->appendName('description', '');
$this->headTitle($this->escapeHtml($title));
$this->pageBreadcrumbs()->setItems([
    'Home' => $this->url('home'),
    'Aportaciones' => $this->url('aportacion'),
]);
// Css Requerido
$this->headLink()
    // Css Select2
    ->prependStylesheet($this->basePath('assets/css/plugins/select2.min.css'))
    // Css DataTables
    ->prependStylesheet($this->basePath('assets/css/plugins/responsive.bootstrap4.min.css'))
    ->prependStylesheet($this->basePath('assets/css/plugins/dataTables.bootstrap4.min.css'));
// Js Requerido
$this->inlineScript()
    // Js de la vista
    ->prependFile($this->basePath('js/catastro/aportacion/index.js'))
    // Js Select2
    ->prependFile($this->basePath('assets/js/plugins/select2.full.min.js'))
    // Css DataTables
    //->prependFile($this->basePath('assets/js/pages/data-responsive-custom.js'))
    ->prependFile($this->basePath('assets/js/plugins/dataTables.responsive.min.js'))
    ->prependFile($this->basePath('assets/js/plugins/dataTables.bootstrap4.min.js'))
    ->prependFile($this->basePath('assets/js/plugins/jquery.dataTables.min.js'));
?>
<!-- [ col ] start -->
<style>
.dataTables_filter
    {
    display: none;
    }
</style>
<div class="col-md-12">
    <div class="card">
        <div class="card-header">
            <h5><?= $title ?></h5>
        </div>
        <div class="card-body">
        <a href="<?= $this->url('aportacion/nueva-aportacion');?>"><button type="button="class="btn btn-success float-right" data-toggle="tooltip" title="Agregar Aportacion" id="cancelar"><i class="fas fa-file-medical"></i></button></a>
            <div class="row">
                <div class="col-sm-2">
                    <div class="form-group ">
                        <!-- <select class="custom-select w-30" id="buscarAportacion" onchange="validacioninput()" class="form-control" name=""> -->
                        <select class="custom-select w-30" id="buscarAportacion" class="form-control" name="">
                            <option value="">Buscar por...</option>
                            <option value="0">ID-Aportacion</option>
                            <option value="1">Parcela</option>
                            <option value="2">Contribuyente.</option>
                            <option value="3">Por Propietario</option>
                        </select>
                    </div>
                </div>
                <div class="col-sm-3">
                    <div class="form-group ">
                        <input class="form-control" type="text" name="" id="query">
                        <input class="form-control" type="hidden" name="" id="query2">
                    </div>
                </div>
            </div>
            <table class="display table table-striped table-hover dt-responsive nowrap" id="aportaciones" style="width:100%">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Parcela</th>
                        <th>Contribuyente</th>
                        <th>Propietario</th>
                        <th>Lote</th>
                        <th>Ultimo Año Pagado</th>
                        <th>Estatus</th>
                        <th>Opciones</th>
                    </tr>
                </thead>
                <tbody id="tdbody">
                </tbody>
            </table>
        </div>
    </div>
</div>
<!-- [ col] end -->
<?= $this->partial('catastro/aportacion/modal') ?>

