<?php
$title = $this->translate('Aportaciones');
$this->headMeta()->appendName('keywords', '');
$this->headMeta()->appendName('description', '');
$this->headTitle($this->escapeHtml($title));
$this->pageBreadcrumbs()->setItems([
    'Home' => $this->url('home'),
    'Aportaciones' => $this->url('aportacion'),
]);
// Css Requerido
$this->headLink()
    // Css Select2
    ->prependStylesheet($this->basePath('assets/css/plugins/select2.min.css'))
    // Css DataTables
    ->prependStylesheet($this->basePath('assets/css/plugins/responsive.bootstrap4.min.css'))
    ->prependStylesheet($this->basePath('assets/css/plugins/dataTables.bootstrap4.min.css'));
// Js Requerido
$this->inlineScript()
    // Js de la vista
    ->prependFile($this->basePath('js/catastro/aportacion/index.js'))
    // Js Select2
    ->prependFile($this->basePath('assets/js/plugins/select2.full.min.js'))
    // Css DataTables
    ->prependFile($this->basePath('assets/js/pages/data-responsive-custom.js'))
    ->prependFile($this->basePath('assets/js/plugins/dataTables.responsive.min.js'))
    ->prependFile($this->basePath('assets/js/plugins/dataTables.bootstrap4.min.js'))
    ->prependFile($this->basePath('assets/js/plugins/jquery.dataTables.min.js'));
?>
<!-- [ col ] start -->
<div class="col-md-12">
    <div class="card">
        <div class="card-header">
            <h5><?= $title ?></h5>
        </div>
        <div class="card-body">
            <div class="row">
                <div class="col-md-1 col-xs-12 mb-4" aling="center">
                    <button type="button" class="btn btn-success" data-toggle="modal" data-target="#MyModal">Consultar</button>
                </div>
            </div>
            <table class="display table table-striped table-hover dt-responsive nowrap" id="aportaciones" style="width:100%">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Contribuyente</th>
                        <th>Titular</th>
                        <th>Vigencia</th>
                        <th>pago de Aportacion</th>
                        <th>Estatus</th>
                        <th>Opciones</th>
                    </tr>
                </thead>
                <tbody>
                    <?php if ($aportaciones): ?>
                        <?php foreach ($aportaciones as $aportacion):?>
                            <tr>
                                <td><?= $aportacion->getIdAportacion() ?></td>
                                <td><?= $aportacion->getIdContribuyente()->getNombre()?></td>
                                <td><?= $aportacion->getIdPredio()->getTitular()?></td>
                                <td><?= $aportacion->getFecha()->format('d-m-Y'); ?></td>
                                <td>$<?= $aportacion->getPago()?></td>
                                <td>
                                    <?php if ($aportacion->getEstatus() == 1) { ?><span class="badge badge-light-success">Verificado</span><?php } ?>
                                    <?php if ($aportacion->getEstatus() == 2) { ?><span class="badge badge-light-danger">Cancelado</span><?php } ?>
                                    <?php if ($aportacion->getEstatus() == 3) { ?><span class="badge badge-light-warning">En Proceso</span><?php } ?>
                                </td>
                                <td>
                                    <a href="<?= $this->url('aportacion/pdf', ['action' => 'pdfdirector', 'id' => $aportacion->getIdAportacion()]); ?>"><button type="button="class="btn btn-primary"<?php if ($aportacion->getEstatus() == 2 || $aportacion->getEstatus()== 3) { ?> disabled <?php } ?>>Imprimir</button></a>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    <?php else: ?>
                        <tr>
                            <td>No hay datos...</td>
                        </tr>
                    <?php endif; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>
<!-- [ col] end -->
<?= $this->partial('catastro/aportacion/modal') ?>
