<?php
$title = $this->translate('Aportaciones');
// meta palabras claves
$this->headMeta()->appendName('keywords', '');
// meta descripción
$this->headMeta()->appendName('description', '');
// titulo de pagina
$this->headTitle($this->escapeHtml($title));
// migas de pan
$this->pageBreadcrumbs()->setItems([
   // 'Inicio' => $this->url('inicio'),
    'Aportaciones' => $this->url('aportacion'),
]);
$this->headLink()
    // Css DataTables
    ->prependStylesheet($this->basePath('assets/css/plugins/responsive.bootstrap4.min.css'))
    ->prependStylesheet($this->basePath('assets/css/plugins/dataTables.bootstrap4.min.css'));
// Js Requerido
$this->inlineScript()
 // Js de la vista
    ->prependFile($this->basePath('js/catastro/aportacion/validation.js'))
    // Css DataTables
    ->prependFile($this->basePath('assets/js/pages/data-responsive-custom.js'))
    ->prependFile($this->basePath('assets/js/plugins/dataTables.responsive.min.js'))
    ->prependFile($this->basePath('assets/js/plugins/dataTables.bootstrap4.min.js'))
    ->prependFile($this->basePath('assets/js/plugins/jquery.dataTables.min.js'));

?>

<div class="col-md-12">
    <div class="card">
        <div class="card-header">
            <h5><?= $title ?></h5>
        </div>
        <div class="card-body">
            <div class="row">
            </div>
            <table id="res-config" class="display table table-striped table-hover dt-responsive nowrap" style="width:100%">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Contribuyente</th>
                        <th>Titular</th>
                        <th>Fecha</th>
                        <th>Opciones</th>
                    </tr>
                </thead>
                <tbody>
                    <?php if ($aportaciones): ?>
                        <?php foreach ($aportaciones as $aportacion): ?>
                            <?php
                            ?>
                            <tr>
                                <td><?= $aportacion->getIdAportacion()?></td>
                                <td><?= $aportacion->getIdContribuyente()->getNombre() ?></td>
                                <td><?= $aportacion->getIdPredio()->getTitular()?></td>
                                <td><?= $aportacion->getFecha()->format('d-m-Y');  ?></td>
                                <td>
                                    <div class="row">
                                    <?php if ($aportacion->getEstatus() == 3) {?>
                                        <!-- <a href="" class="btn btn-primary">Ver</a> -->
                                        <a href="<?= $this->url('aportacion/pdfdirrector', ['action' => 'pdfdirrector', 'id' => $aportacion->getIdAportacion()]); ?>"><button type="button="class="btn btn-primary">ver</button></a>
                                        <!-- <button type="button" class="btn btn-secondary" id="button" data-toggle="modal" data-target="#myModal">
                                        Modificar
                                        </button> -->
                                        <a href="<?= $this->url('aportacion/editar', ['action' => 'editar', 'id' => $aportacion->getIdAportacion()]); ?>" class="btn btn-secondary" data-toggle="modal"  onclick="edit_validation('<?= $aportacion->getIdAportacion() ?>')">Modificar</a>
                                        <?= $this->form()->openTag($form); ?>
                                        <?= $this->formHidden($form->get('padron_id')->setValue($aportacion->getIdAportacion())); ?>
                                        <?= $this->formHidden($form->get('status')->setValue("1"));?>
                                        <?= $this->formHidden($form->get('csrf')); ?>
                                        <div class="text-danger">
                                            <?= $this->formElementErrors($form->get('csrf')); ?>
                                        </div>
                                        <?= $this->formButton($form->get('confirmar')->setAttributes(['class' => 'btn btn-success'])->setOptions(['label' => '<i class="feather mr-2 icon-check-circle"></i> Confirmar', 'label_options' => ['disable_html_escape' => true,]])); ?>
                                        <?= $this->form()->closeTag(); ?>
                                        <?= $this->form()->openTag($form); ?>
                                        <?= $this->formHidden($form->get('padron_id')->setValue($aportacion->getIdAportacion())); ?>
                                        <?= $this->formHidden($form->get('status')->setValue("2")); ?>
                                        <?= $this->formHidden($form->get('csrf')); ?>
                                        <div class="text-danger">
                                            <?= $this->formElementErrors($form->get('csrf')); ?>
                                        </div>
                                        <?= $this->formButton($form->get('confirmar')->setAttributes(['class' => 'btn btn-danger '])->setOptions(['label' => '<i class="feather mr-2 icon-x-circle"></i> Cancelar', 'label_options' => ['disable_html_escape' => true,]])); ?>
                                        <?php
                                        }else{
                                        ?>
                                        <a href="<?= $this->url('aportacion/pdfdirrector', ['action' => 'pdfdirrector', 'id' => $aportacion->getIdAportacion()]); ?>"><button type="button="class="btn btn-primary">ver</button></a>
                                        <a href="<?= $this->url('aportacion/editar', ['action' => 'editar', 'id' => $aportacion->getIdAportacion()]); ?>" data-toggle="modal"  onclick="edit_validation('<?= $aportacion->getIdAportacion() ?>')"><button type="button"class="btn btn-secondary"disabled >Modificar</button></a>
                                        <?= $this->formButton($form->get('confirmar')->setAttributes(['class' => 'btn btn-success', 'disabled' => 'true'])->setOptions(['label' => '<i class="feather mr-2 icon-check-circle"></i> Confirmar', 'label_options' => ['disable_html_escape' => true,]])); ?>
                                        <?= $this->formButton($form->get('confirmar')->setAttributes(['class' => 'btn btn-danger ', 'disabled' => 'true'])->setOptions(['label' => '<i class="feather mr-2 icon-x-circle"></i> Cancelar', 'label_options' => ['disable_html_escape' => true,]])); ?>
                                        <?php
                                        }
                                        ?>
                                        <?= $this->form()->closeTag(); ?>
                                    </div>
                            </tr>
                        <?php endforeach; ?>
                    <?php else: ?>
                        <tr>
                            <td>No hay datos</td>
                        </tr>
                    <?php endif; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>
<!-- [ col] end -->
<!-- sweet alert Js -->
<!-- Button trigger modal -->

<?= $this->partial('catastro/aportacion/validationModal') ?>
