<?php
$title = $this->translate('Aportaciones');
// meta palabras claves
$this->headMeta()->appendName('keywords', '');
// meta descripción
$this->headMeta()->appendName('description', '');
// titulo de pagina
$this->headTitle($this->escapeHtml($title));
// migas de pan
$this->pageBreadcrumbs()->setItems([
   // 'Inicio' => $this->url('inicio'),
    'Aportaciones' => $this->url('aportacion'),
]);
$this->headLink()
    // Css DataTables
    ->prependStylesheet($this->basePath('assets/css/plugins/responsive.bootstrap4.min.css'))
    ->prependStylesheet($this->basePath('assets/css/plugins/dataTables.bootstrap4.min.css'));
// Js Requerido
$this->inlineScript()
 // Js de la vista
    ->prependFile($this->basePath('js/catastro/aportacion/validation.js'))
    // Css DataTables
   // ->prependFile($this->basePath('assets/js/pages/data-responsive-custom.js'))
    ->prependFile($this->basePath('assets/js/plugins/dataTables.responsive.min.js'))
    ->prependFile($this->basePath('assets/js/plugins/dataTables.bootstrap4.min.js'))
    ->prependFile($this->basePath('assets/js/plugins/jquery.dataTables.min.js'));

?>
<style>
.dataTables_filter
    {
    display: none;
    }
</style>

<div class="col-md-12">
    <div class="card">
        <div class="card-header">
            <h5><?= $title ?></h5>
        </div>
        <div class="card-body">
            <div class="row">
                <div class="col-sm-2">
                    <div class="form-group ">
                        <select class="custom-select w-30" id="buscarAportacion"  onchange="validacioninput()" class="form-control" name="">
                            <option>Buscar por...</option>
                            <option>ID-Aportacion</option>
                            <option>Contribuyente.</option>
                            <option>Por Propietario</option>
                            <option>Parcela</option>
                        </select>
                    </div>
                </div>
                <div class="col-sm-3">
                    <div class="form-group ">
                        <input class="form-control" type="text" name="" id="query">
                        <input class="form-control" type="hidden" name="" id="query2">
                    </div>
                </div>
            </div>
            <table id="validation" class="display table table-striped table-hover dt-responsive nowrap" style="width:100%">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Parcela</th>
                        <th>Contribuyente</th>
                        <th>Propietario</th>
                        <th>Lote</th>
                        <th>Ultimo Año Pagado</th>
                        <th>Opciones</th>
                    </tr>
                </thead>
                <tbody id="tbody">
                </tbody>
            </table>
        </div>
    </div>
</div>
<!-- [ col] end -->
<!-- sweet alert Js -->
<!-- Button trigger modal -->

<?= $this->partial('catastro/aportacion/validationModal') ?>
