<?php
$title = $this->translate('Agregar');
$this->headMeta()->appendName('keywords', '');
$this->headMeta()->appendName('description', '');
$this->headTitle($this->escapeHtml($title));
$this->pageBreadcrumbs()->setItems([
    'Home' => $this->url('home'),
    'Contribuyentes' => $this->url('contribuyente'),
    'Agregar' => $this->url('contribuyente/agregar'),
]);
// Css Requerido
$this->headLink()
    // Css Select2
    ->prependStylesheet($this->basePath('assets/css/plugins/select2.min.css'));
// Js Requerido
$this ->inlineScript()
    // Js de la vista
    ->prependFile($this->basePath('js/catastro/contribuyente/add.js'))
    // Js Select2
    ->prependFile($this->basePath('assets/js/plugins/select2.full.min.js'));
// Instancia del form
$form = $this->form;
$form->setAttribute('action', $this->url('contribuyente/agregar'));
$form->prepare();
?>
<!-- [ col ] start -->
<div class="col-md-6">
    <div class="card">
        <div class="card-header">
            <h5><?= $title ?></h5>
        </div>
        <div class="card-body">
            <!-- [ openTag ] start -->
            <?= $this->form()->openTag($form); ?>
                <div class="form-group">
                <?= $this->formLabel($form->get('persona')); ?>
                <?= $this->formSelect($form->get('persona')->setAttributes(['class' => "custom-select js-select2-persona col-sm-12"])); ?>
                <?= $this->formElementErrors($form->get('persona')); ?>
                </div>
                <hr>
                <div class="form-group">
                    <?= $this->formLabel($form->get('nombre')); ?>
                    <?= $this->formText($form->get('nombre')); ?>
                    <?= $this->formElementErrors($form->get('nombre', ['class' => 'text-danger'])); ?>
                </div>
                <div class="form-group">
                    <?= $this->formLabel($form->get('apellido_paterno')); ?>
                    <?= $this->formText($form->get('apellido_paterno')); ?>
                    <?= $this->formElementErrors($form->get('apellido_paterno')); ?>
                </div>
                <div class="form-group">
                    <?= $this->formLabel($form->get('apellido_materno')); ?>
                    <?= $this->formText($form->get('apellido_materno')); ?>
                    <?= $this->formElementErrors($form->get('apellido_materno')); ?>
                </div>
                <div class="form-group">
                    <?= $this->formLabel($form->get('rfc')); ?>
                    <?= $this->formText($form->get('rfc')); ?>
                    <?= $this->formElementErrors($form->get('rfc')); ?>
                </div>
                <div class="form-group">
                    <?= $this->formLabel($form->get('curp')); ?>
                    <?= $this->formText($form->get('curp')); ?>
                    <?= $this->formElementErrors($form->get('curp')); ?>
                </div>
                <div class="form-group">
                    <?= $this->formLabel($form->get('razon_social')); ?>
                    <?= $this->formText($form->get('razon_social')); ?>
                    <?= $this->formElementErrors($form->get('razon_social')); ?>
                </div>
                <div class="form-group">
                    <?= $this->formLabel($form->get('correo')); ?>
                    <?= $this->formText($form->get('correo')); ?>
                    <?= $this->formElementErrors($form->get('correo')); ?>
                </div>
                <div class="form-group">
                    <?= $this->formLabel($form->get('telefono')); ?>
                    <?= $this->formText($form->get('telefono')); ?>
                    <?= $this->formElementErrors($form->get('telefono')); ?>
                </div>
                <div class="form-group">
                    <?= $this->formLabel($form->get('genero')); ?>
                    <?= $this->formText($form->get('genero')); ?>
                    <?= $this->formElementErrors($form->get('genero')); ?>
                </div>
                <?= $this->formHidden($form->get('csrf')); ?>
                <?= $this->formElementErrors($form->get('csrf')); ?>
                <?= $this->formSubmit($form->get('btnGuardar')); ?>
                <a href="<?= $this->url("contribuyente") ?>" class="btn btn-secondary"> Volver atrás</a>
            <!-- [ closeTag ] start -->
        </div>
    </div>
</div>
<!-- [ col] end -->

<div class="col-md-6">
    <div class="card">
        <div class="card-body">
            <!-- [ openTag ] start -->
                <div class="form-group">
                    <?= $this->formText($form->get('input1')); ?>
                    <?= $this->formElementErrors($form->get('input1')); ?>
                </div>
                <hr>
                <?= $this->formLabel($form->get('archivo')); ?>
                <div class="form-group" id="select">
                    <div class="input-group">
                        <div class="input-group-append delete">
                            <span class="input-group-text" title="Remove this field"><i class="fas fa-times"></i></span>
                        </div>
                        <?= $this->formSelect($form->get('id_archivo_categoria')->setName("id_archivo_categoria[]")->setValueOptions($this->categorias)); ?>
                        <div class="file-loading">
                            <?= $this->formFile($form->get('archivo')); ?>
                        </div>
                        <div class="text-danger">
                            <?= $this->formElementErrors($form->get('archivo')); ?>
                        </div>
                    </div>
                </div>

                <div id="additionalselects">
                    <!-- dynamically created archivos field will be placed here -->
                </div>
                <div class="btn-group float-right">

                <?= $this->formButton($form->get('add_more')); ?>
            <?= $this->form()->closeTag(); ?>
            <!-- [ closeTag ] start -->
        </div>
    </div>
</div>
<!-- [ col] end -->
