<?php
$title = $this->translate('Agregar');
$this->headMeta()->appendName('keywords', '');
$this->headMeta()->appendName('description', '');
$this->headTitle($this->escapeHtml($title));
$this->pageBreadcrumbs()->setItems([
    'Home' => $this->url('home'),
    'Contribuyentes' => $this->url('contribuyente'),
    'Agregar' => $this->url('contribuyente/agregar'),
]);
// Css Requerido
$this->headLink()
    // Css Select2
    ->prependStylesheet($this->basePath('assets/css/plugins/select2.min.css'));
// Js Requerido
$this ->inlineScript()
    // Js de la vista
    ->prependFile($this->basePath('js/catastro/contribuyente/add.js'))
    // Js Select2
    ->prependFile($this->basePath('assets/js/plugins/select2.full.min.js'));
// Instancia del form
$form = $this->form;
$form->setAttribute('action', $this->url('contribuyente/agregar'));
$form->prepare();
?>
<!-- [ col ] start -->
<div class="col-md-12">
    <div class="card">
        <div class="card-header">
            <h5><?= $title ?></h5>
        </div>
        <div class="card-body">
            <!-- [ openTag ] start -->
            <?= $this->form()->openTag($form); ?>
                <div class="form-group">
                    <?= $this->formLabel($form->get('persona')); ?>
                    <?= $this->formSelect($form->get('persona')->setAttributes(['class' => "custom-select js-select2-persona col-sm-12"])); ?>
                    <?= $this->formElementErrors($form->get('persona')); ?>
                </div>
                <div class="form-group">
                    <?= $this->formText($form->get('input1')); ?>
                    <?= $this->formElementErrors($form->get('input1')); ?>
                </div>
                <hr>
                <div class="form-row">
                    <div class="form-group col-md-3">
				        <?= $this->formLabel($form->get('tipo_persona')); ?>
                        <?= $this->formSelect($form->get('tipo_persona')); ?>
                        <?= $this->formElementErrors($form->get('tipo_persona')); ?>
                    </div>
                    <div class="form-group col-md-3" id="pNombre">
                        <?= $this->formLabel($form->get('nombre')); ?>
                        <?= $this->formText($form->get('nombre')); ?>
                        <div class="text-danger">
                        <?= $this->formElementErrors($form->get('nombre')); ?>
                        </div>
                    </div>
                    <div class="form-group col-md-3" id="aPaterno">
                        <?= $this->formLabel($form->get('apellido_paterno')); ?>
                        <?= $this->formText($form->get('apellido_paterno')); ?>
                        <div class="text-danger">
                        <?= $this->formElementErrors($form->get('apellido_paterno')); ?>
                        </div>
                    </div>
                    <div class="form-group col-md-3" id="aMaterno">
                        <?= $this->formLabel($form->get('apellido_materno')); ?>
                        <?= $this->formText($form->get('apellido_materno')); ?>
                        <div class="text-danger">
                        <?= $this->formElementErrors($form->get('apellido_materno')); ?>
                        </div>
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-3">
                        <?= $this->formLabel($form->get('rfc')); ?>
                        <?= $this->formText($form->get('rfc')); ?>
                        <div class="text-danger">
                        <?= $this->formElementErrors($form->get('rfc')); ?>
                        </div>
                    </div>
                    <div class="form-group col-md-9">
                        <?= $this->formLabel($form->get('razon_social')); ?>
                        <?= $this->formText($form->get('razon_social')); ?>
                        <div class="text-danger">
                        <?= $this->formElementErrors($form->get('razon_social')); ?>
                        </div>
                    </div>
                </div>
                <div class="form-row" id="pFisica">
                    <div class="form-group col-md-3">
                        <?= $this->formLabel($form->get('curp')); ?>
                        <?= $this->formText($form->get('curp')); ?>
                        <div class="text-danger">
                        <?= $this->formElementErrors($form->get('curp')); ?>
                        </div>
                    </div>
                    <div class="form-group col-md-6">
                        <?= $this->formLabel($form->get('fecha_nacimiento')); ?>
                        <div>
                        <?= $this->formDateSelect($form->get('fecha_nacimiento')); ?>
                        </div>
                        <div class="text-danger">
                        <?= $this->formElementErrors($form->get('fecha_nacimiento')); ?>
                        </div>
                    </div>
                    <div class="form-group col-md-3">
                        <?= $this->formLabel($form->get('genero')); ?>
                        <?= $this->formSelect($form->get('genero')); ?>
                        <div class="text-danger">
                        <?= $this->formElementErrors($form->get('genero')); ?>
                        </div>
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <?= $this->formLabel($form->get('correo')); ?>
                        <?= $this->formText($form->get('correo')); ?>
                        <div class="text-danger">
                        <?= $this->formElementErrors($form->get('correo')); ?>
                        </div>
                    </div>
                    <div class="form-group col-md-6">
                        <?= $this->formLabel($form->get('telefono')); ?>
                        <?= $this->formText($form->get('telefono')); ?>
                        <div class="text-danger">
                        <?= $this->formElementErrors($form->get('telefono')); ?>
                        </div>
                    </div>
                    <div class="form-group col-md-4">

                    </div>
                </div>
                <?= $this->formHidden($form->get('csrf')); ?>
                <div class="text-danger">
                <?= $this->formElementErrors($form->get('csrf')); ?>
                </div>
                <?= $this->formSubmit($form->get('btnGuardar')); ?>
                <a href="<?= $this->url("contribuyente") ?>" class="btn btn-secondary"> Volver atrás</a>
            <!-- [ closeTag ] start -->
        </div>
    </div>
</div>
<!-- [ col] end -->
