<?php
$title = $this->translate('Editar');
$this->headMeta()->appendName('keywords', '');
$this->headMeta()->appendName('description', '');
$this->headTitle($this->escapeHtml($title));
$this->pageBreadcrumbs()->setItems([
    'Home' => $this->url('home'),
    'Contribuyentes' => $this->url('contribuyente'),
    'Editar' => $this->url('contribuyente/editar'),
]);
?>
<!-- [ col ] start -->
<div class="col-md-12">
    <div class="card">
        <div class="card-header">
            <h5><?= $title ?></h5>
        </div>
        <div class="card-body">
            <!-- [ openTag ] start -->
            <?= $this->form()->openTag($form); ?>
                <div class="form-row">
                    <div class="form-group col-md-3">
				        <?= $this->formLabel($form->get('tipo_persona')); ?>
                        <?= $this->formSelect($form->get('tipo_persona')); ?>
                        <?= $this->formElementErrors($form->get('tipo_persona')); ?>
                    </div>
                    <div class="form-group col-md-3" id="pNombre">
                        <?= $this->formLabel($form->get('nombre')); ?>
                        <?= $this->formText($form->get('nombre')); ?>
                        <div class="text-danger">
                            <?= $this->formElementErrors($form->get('nombre')); ?>
                        </div>
                    </div>
                    <div class="form-group col-md-3" id="aPaterno">
                        <?= $this->formLabel($form->get('apellido_paterno')); ?>
                        <?= $this->formText($form->get('apellido_paterno')); ?>
                        <div class="text-danger">
                            <?= $this->formElementErrors($form->get('apellido_paterno')); ?>
                        </div>
                    </div>
                    <div class="form-group col-md-3" id="aMaterno">
                        <?= $this->formLabel($form->get('apellido_materno')); ?>
                        <?= $this->formText($form->get('apellido_materno')); ?>
                        <div class="text-danger">
                            <?= $this->formElementErrors($form->get('apellido_materno')); ?>
                        </div>
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-3">
                        <?= $this->formLabel($form->get('rfc')); ?>
                        <?= $this->formText($form->get('rfc')); ?>
                        <div class="text-danger">
                            <?= $this->formElementErrors($form->get('rfc')); ?>
                        </div>
                    </div>
                    <div class="form-group col-md-9">
                        <?= $this->formLabel($form->get('razon_social')); ?>
                        <?= $this->formText($form->get('razon_social')); ?>
                        <div class="text-danger">
                            <?= $this->formElementErrors($form->get('razon_social')); ?>
                        </div>
                    </div>
                </div>
                <div class="form-row" id="pFisica">
                    <div class="form-group col-md-3">
                        <?= $this->formLabel($form->get('curp')); ?>
                        <?= $this->formText($form->get('curp')); ?>
                        <div class="text-danger">
                            <?= $this->formElementErrors($form->get('curp')); ?>
                        </div>
                    </div>
                    <div class="form-group col-md-5">
                        <?= $this->formLabel($form->get('fecha_nacimiento')); ?>
                        <div>
                        <?= $this->formDateSelect($form->get('fecha_nacimiento')); ?>
                        </div>
                        <div class="text-danger">
                            <?= $this->formElementErrors($form->get('fecha_nacimiento')); ?>
                        </div>
                    </div>
                    <div class="form-group col-md-2">
                        <?= $this->formLabel($form->get('genero')); ?>
                        <?= $this->formSelect($form->get('genero')); ?>
                        <div class="text-danger">
                        <?= $this->formElementErrors($form->get('genero')); ?>
                        </div>
                    </div>
                    <div class="form-group col-md-2">
                        <?= $this->formLabel($form->get('estado_civil')); ?>
                        <?= $this->formSelect($form->get('estado_civil')); ?>
                        <div class="text-danger">
                            <?= $this->formElementErrors($form->get('estado_civil')); ?>
                        </div>
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <?= $this->formLabel($form->get('correo')); ?>
                        <?= $this->formText($form->get('correo')); ?>
                        <div class="text-danger">
                        <?= $this->formElementErrors($form->get('correo')); ?>
                        </div>
                    </div>
                    <div class="form-group col-md-6">
                        <?= $this->formLabel($form->get('telefono')); ?>
                        <?= $this->formText($form->get('telefono')); ?>
                        <div class="text-danger">
                        <?= $this->formElementErrors($form->get('telefono')); ?>
                        </div>
                    </div>
                    <div class="form-group col-md-4">

                    </div>
                </div>
                <?= $this->formHidden($form->get('csrf')); ?>
                <div class="text-danger">
                <?= $this->formElementErrors($form->get('csrf')); ?>
                </div>
                <?= $this->formSubmit($form->get('btnGuardar')); ?>
                <a href="<?= $this->url("contribuyente") ?>" class="btn btn-secondary"> Volver atrás</a>
            <?= $this->form()->closeTag(); ?>
            <!-- [ closeTag ] start -->
        </div>
    </div>
</div>
<!-- [ col] end -->
