<?php
$title = $this->translate('Contribuyentes');
$this->headMeta()->appendName('keywords', '');
$this->headMeta()->appendName('description', '');
$this->headTitle($this->escapeHtml($title));
$this->pageBreadcrumbs()->setItems([
    'Home' => $this->url('home'),
    'Contribuyentes' => $this->url('contribuyente'),
]);
// Css Requerido
$this->headLink()
    // Css DataTables
    ->prependStylesheet($this->basePath('assets/css/plugins/responsive.bootstrap4.min.css'))
    ->prependStylesheet($this->basePath('assets/css/plugins/dataTables.bootstrap4.min.css'));
$this->inlineScript()
    // Js de la vista
    ->prependFile($this->basePath('js/catastro/contribuyente/index.js'))
    // ->prependFile($this->basePath('js/catastro/contribuyente/add.js'))
    // TODO: Pasar scripts al index
    ->prependFile($this->basePath('js/catastro/contribuyente/view.js'))
    ->prependFile($this->basePath('js/catastro/contribuyente/edit.js'))
    ->prependFile($this->basePath('js/catastro/contribuyente/delete.js'))
    // Js DataTables
    // ->prependFile($this->basePath('assets/js/pages/data-responsive-custom.js'))
    ->prependFile($this->basePath('assets/js/plugins/dataTables.responsive.min.js'))
    ->prependFile($this->basePath('assets/js/plugins/dataTables.bootstrap4.min.js'))
    ->prependFile($this->basePath('assets/js/plugins/jquery.dataTables.min.js'))
    ;
?>

<!-- [ col ] start -->
<div class="col-md-12">
    <div class="card">
        <div class="card-header">
            <h5><?= $title ?></h5>
        </div>
        <div class="card-body">
            <div class="row">
                <div class="col-12">
                    <a href="<?= $this->url("contribuyente/agregar") ?>" class="btn btn-secondary btn-sm float-right"><i class="fas fa-plus fa-fw"></i></a>
                </div>
            </div>
            <br>
            <table class="display table table-striped table-hover" id="contribuyentes" style="width:100%">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Nombre</th>
                        <th>R.F.C</th>
                        <th>C.U.R.P.</th>
                        <th>Tipo Persona</th>
                        <th>Opciones</th>
                    </tr>
                </thead>
                <tbody>
                    <?php if (!empty($contribuyentes)): ?>
                        <?php foreach ($contribuyentes as $contribuyente): ?>
                            <tr>
                                <td><?= $contribuyente->getIdContribuyente() ?></td>
                                <td><?= $contribuyente->getNombre() ?></td>
                                <td><?= $contribuyente->getRfc() ?></td>
                                <td><?= $contribuyente->getCurp() ?></td>
                                <td><?= $contribuyente->getTipoPersona() ?></td>
                                <td>
                                    <div class="btn-group">
                                        <a href="<?= $this->url('contribuyente/ver', ['action' => 'ver', 'id' => $contribuyente->getIdContribuyente()]); ?>" class="btn btn-info btn-sm" title="Detalle"><i class="fas fa-folder-open fa-fw"></i></a>
                                        <!-- <a href="<?= $this->url('contribuyente/eliminar', ['action' => 'eliminar', 'id' => $contribuyente->getIdContribuyente()]); ?>" class="btn btn-danger btn-sm" title="Eliminar" data-toggle="modal" data-target="#deleteModal" data-id="<?= $contribuyente->getIdContribuyente() ?>" ><i class="fas fa-times fa-fw"></i></a> -->
                                    </div>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    <?php else: ?>
                        <tr class="text-center">
                            <td colspan="6">No hay datos...</td>
                        </tr>
                    <?php endif; ?>
                </tbody>
            </table>
            <div class="float-right" id="lv-links">
                <?= $this->paginationControl($contribuyentes, 'Sliding', 'catastro/partial/paginator', ['route' => 'contribuyente']); ?>
            </div>
        </div>
    </div>
</div>
<!-- [ col] end -->

<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteModalLabel"></h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>Esta apunto de realizar una acción irreversible hasta para el administrador.</p>
                <p>¿Desea continuar?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger btn-ok">Confirmar</button>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
            </div>
        </div>
    </div>
</div>
