<?php
$title = $this->translate('Contribuyentes');
$this->headMeta()->appendName('keywords', '');
$this->headMeta()->appendName('description', '');
$this->headTitle($this->escapeHtml($title));
$this->pageBreadcrumbs()->setItems([
    'Home' => $this->url('home'),
    'Contribuyentes' => $this->url('contribuyente'),
]);
// Hoja de estilos requerido
$this->headLink()
    // Css DataTables
    ->prependStylesheet($this->basePath('assets/css/plugins/responsive.bootstrap4.min.css'))
    ->prependStylesheet($this->basePath('assets/css/plugins/dataTables.bootstrap4.min.css'));
$this->inlineScript()
    // Js de la vista
    ->prependFile($this->basePath('js/catastro/contribuyente/index.js'))
    ->prependFile($this->basePath('js/catastro/contribuyente/add.js'))
    ->prependFile($this->basePath('js/catastro/contribuyente/view.js'))
    ->prependFile($this->basePath('js/catastro/contribuyente/edit.js'))
    ->prependFile($this->basePath('js/catastro/contribuyente/delete.js'))
    // Js DataTables
    ->prependFile($this->basePath('assets/js/pages/data-responsive-custom.js'))
    ->prependFile($this->basePath('assets/js/plugins/dataTables.responsive.min.js'))
    ->prependFile($this->basePath('assets/js/plugins/dataTables.bootstrap4.min.js'))
    ->prependFile($this->basePath('assets/js/plugins/jquery.dataTables.min.js'))
    ;
?>
<!-- [ col ] start -->
<div class="col-md-12">
    <div class="card">
        <div class="card-header">
            <h5><?= $title ?></h5>
        </div>
        <div class="card-body">
            <div class="row">
                <div class="col-md-1 col-xs-12 mb-4" align=center>
                    <div class="btn-group" role="group" aria-label="Botones">
                        <a href="<?= $this->url("contribuyente/agregar") ?>" class="btn btn-primary" data-toggle="modal" onClick="add_contribuyente()">Agregar</a>
                        <a href="<?= $this->url("contribuyente/pdf") ?>" class="btn btn-danger">PDF</a>
                        <a href="<?= $this->url("contribuyente/excel") ?>" class="btn btn-success">Excel</a>
                    </div>
                </div>
            </div>
            <!-- <table class="table table-striped table-bordered nowrap" id="contribuyentes"> -->
            <table  class="display table table-striped table-hover dt-responsive nowrap" id="contribuyentes" style="width:100%">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Nombre</th>
                        <th>Apellido Paterno</th>
                        <th>Apellido Materno</th>
                        <th>Genero</th>
                        <th>Opciones</th>
                    </tr>
                </thead>
                <tbody>

                </tbody>
            </table>
            <div class="float-right" id="lv-links">
                <!-- <?php //echo $this->paginationControl($contribuyentes, 'Sliding', 'catastro/partial/paginator', ['route' => 'contribuyente']);?> -->
            </div>
        </div>
    </div>
</div>
<!-- [ col] end -->

