<?php
$title = $this->translate('Detalle');
$this->headMeta()->appendName('keywords', '');
$this->headMeta()->appendName('description', '');
$this->headTitle($this->escapeHtml($title));
$this->pageBreadcrumbs()->setItems([
    'Home' => $this->url('home'),
    'Contribuyentes' => $this->url('contribuyente'),
    'Detalle' => $this->url('contribuyente/ver'),
]);
// Css Requerido
$this->headLink()
    // Css FileInput
    ->prependStylesheet($this->basePath('js/plugins/FileInput/css/fileinput.min.css'))
    ;
// Js Requerido
$this ->inlineScript()
    // Js de la vista
    ->prependFile($this->basePath('js/catastro/contribuyente/view.js'))
    // Js FileInput
    ->prependFile($this->basePath('js/plugins/FileInput/js/locales/es.js'))
    ->prependFile($this->basePath('js/plugins/FileInput/js/fileinput.min.js'))
    // Js notification
    ->prependFile($this->basePath('assets/js/plugins/bootstrap-notify.min.js'))
    ;
?>
<!-- [ col ] start -->
<div class="col-md-12">
    <div class="card">
        <div class="card-header">
            <h5><?= $title ?> Contribuyente</h5>
        </div>
        <div class="card-body">
            <table class="table table-striped table-bordered" id="tablaDatos">
                <tbody>
                    <tr>
                        <td>Nombre</td>
                        <td><?= $contribuyente->getNombre() ?></td>
                    </tr>
                    <?php if ($contribuyente->getTipoPersona() == 'F'): ?>
                    <tr>
                        <td>Apellido Paterno</td>
                        <td><?= $contribuyente->getApellidoPaterno() ?></td>
                    </tr>
                    <tr>
                        <td>Apellido Materno</td>
                        <td><?= $contribuyente->getApellidoMaterno() ?></td>
                    </tr>
                    <?php endif; ?>
                    <tr>
                        <td>Razon Social</td>
                        <td><?= $contribuyente->getRazonSocial() ?></td>
                    </tr>
                    </tr>
                    <tr>
                        <td>R.F.C.</td>
                        <td><?= $contribuyente->getRfc() ?></td>
                    </tr>
                    </tr>
                    <?php if ($contribuyente->getTipoPersona() == 'F'): ?>
                    <tr>
                        <td>C.U.R.P.</td>
                        <td><?= $contribuyente->getCurp() ?></td>
                    </tr>
                    <tr>
                        <td>Genero</td>
                        <td>
                            <?php echo  $contribuyente->getGenero() == 'H' ? 'Hombre' : '' ?>
                            <?php echo  $contribuyente->getGenero() == 'M' ? 'Mujer' : '' ?>
                            <?php echo  $contribuyente->getGenero() == 'O' ? 'Otro' : '' ?>
                        </td>
                    </tr>
                    <?php endif; ?>
                    <tr>
                        <td>Correo Electrónico</td>
                        <td><?= $contribuyente->getCorreo() ?></td>
                    </tr>
                    <tr>
                        <td>Telefono</td>
                        <td><?= $contribuyente->getTelefono() ?></td>
                    </tr>
                    <tr>
                        <td>Fecha de Alta</td>
                        <td><?= $contribuyente->getCreatedAt()->format('Y-m-d h:m:s')  ?></td>
                    </tr>
                    <tr>
                        <td>Fecha Ultima Modificación</td>
                        <td><?= $contribuyente->getUpdatedAt()->format('Y-m-d h:m:s')  ?></td>
                    </tr>

                </tbody>
            </table>
            <a href="<?= $this->url("contribuyente") ?>" class="btn btn-secondary"> Volver atrás</a>
            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#editarModal" onClick="editar('<?= $contribuyente->getIdContribuyente() ?>')">
              Editar datos
            </button>
        </div>
    </div>
</div>
<!-- [ col ] end -->

<!-- [ col ] start -->
<div class="col-md-12">
    <div class="card">
        <div class="card-header">
            <h5>Archivos</h5>
            <div class="float-right">
                <button id="agregar-archivo" class="btn btn-success btn-sm" data-toggle="modal" data-target="#subirArchivoModal">Agregar+</button>
            </div>
        </div>
        <div class="card-body">
            <table class="table table-light" id="archivosList">
                <thead class="thead-dark">
                    <tr>
                        <th>Tipo</th>
                        <th>Archivo</th>
                        <th>Fecha de subida</th>
                        <th>Acciones</th>
                    </tr>
                </thead>
                <tbody>
                    <?php if ($archivos): ?>
                        <?php foreach ($archivos as $archivo): ?>
                            <tr>
                                <td><?= $archivo->getIdArchivo()->getIdArchivoCategoria()->getNombre() ?></td>
                                <td><?= $archivo->getIdArchivo()->getUrl() ?></td>
                                <td><?= $archivo->getIdArchivo()->getCreatedAt()->format('Y-m-d h:m:s') ?></td>
                                <td>
                                    <a target="_blank" href="<?= $this->url('biblioteca/ver-archivo', ['archivo'=>'file'], ['query'=>['name'=>$archivo->getIdArchivo()->getUrl()]]); ?>"  class="btn btn-info btn-sm" role="button"> Previsualizar</a>
                                    <a href="<?= $this->url('biblioteca/descargar-archivo', ['action' => 'descargar-archivo', 'archivo' => $archivo->getIdArchivo()->getIdArchivo()]); ?>" class="btn btn-success btn-sm"> Descargar</a>
                                    <a href="<?= $this->url('biblioteca/eliminar-archivo-contribuyente', ['action' => 'eliminar-archivo-contribuyente', 'contribuyente' => $archivo->getIdContribuyente()->getIdContribuyente(), 'archivo' => $archivo->getIdArchivo()->getIdArchivo()]); ?>" class="btn btn-danger btn-sm"> Eliminar</a>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    <?php else: ?>
                        <tr>
                            <td colspan="4" class="text-center">No hay archivos...</td>
                        </tr>
                    <?php endif; ?>
                </tbody>
            </table>

        </div>
    </div>
</div>
<!-- [ col ] end -->

<!-- [ modal ] inicio -->
<div class="modal fade" id="subirArchivoModal" tabindex="-1" role="dialog" aria-labelledby="subirArchivoLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
    <div class="modal-content">
        <div class="modal-header">
        <h5 class="modal-title" id="subirArchivoLabel">Cargar archivo...</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        </div>
        <div class="modal-body">
            <form action="#" method="post" enctype="multipart/form-data" id="subirArchivoForm">
                <div class="form-group">
                    <input type="hidden" name="input1" value="<?= $contribuyenteId ?>">
                </div>
                <div class="form-group">
                    <select class="form-control" id="id_archivo_categoria" name="id_archivo_categoria">
                        <?php foreach($categorias as $categoria): ?>
                            <?= '<option value="'. $categoria->getIdArchivoCategoria() .'">' . $categoria->getNombre() . '</option>'?>
                        <?php endforeach;?>
                    </select>
                </div>
                <div class="form-group">
                    <div class="file-loading">
                        <input type="file" name="archivo" id="archivo">
                    </div>
                </div>
            </form>
        </div>
        <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
        </div>
    </div>
    </div>
</div>
<!-- [ modal ] fin -->

<!-- [ modal ] inicio -->
<div class="modal fade" id="editarModal" tabindex="-1" role="dialog" aria-labelledby="modalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="modalLabel">Editar datos</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
            <?= $this->form()->openTag($form); ?>
                <div class="form-row">
                    <div class="form-group col-md-3">
                        <?= $this->formLabel($form->get('tipo_persona')); ?>
                        <?= $this->formSelect($form->get('tipo_persona')); ?>
                        <?= $this->formElementErrors($form->get('tipo_persona')); ?>
                    </div>
                    <div class="form-group col-md-3" id="pNombre">
                        <?= $this->formLabel($form->get('nombre')); ?>
                        <?= $this->formText($form->get('nombre')); ?>
                        <ul class="text-danger"></ul>
                    </div>
                    <div class="form-group col-md-3" id="aPaterno">
                        <?= $this->formLabel($form->get('apellido_paterno')); ?>
                        <?= $this->formText($form->get('apellido_paterno')); ?>
                        <ul class="text-danger"></ul>
                    </div>
                    <div class="form-group col-md-3" id="aMaterno">
                        <?= $this->formLabel($form->get('apellido_materno')); ?>
                        <?= $this->formText($form->get('apellido_materno')); ?>
                        <ul class="text-danger"></ul>
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-3">
                        <?= $this->formLabel($form->get('rfc')); ?>
                        <?= $this->formText($form->get('rfc')); ?>
                        <ul class="text-danger"></ul>
                    </div>
                    <div class="form-group col-md-9">
                        <?= $this->formLabel($form->get('razon_social')); ?>
                        <?= $this->formText($form->get('razon_social')); ?>
                        <ul class="text-danger"></ul>
                    </div>
                </div>
                <div class="form-row" id="pFisica">
                    <div class="form-group col-md-3">
                        <?= $this->formLabel($form->get('curp')); ?>
                        <?= $this->formText($form->get('curp')); ?>
                        <ul class="text-danger"></ul>
                    </div>
                    <div class="form-group col-md-5">
                        <?= $this->formLabel($form->get('fecha_nacimiento')); ?>
                        <div>
                        <?= $this->formDateSelect($form->get('fecha_nacimiento')); ?>
                        </div>
                        <ul class="text-danger"></ul>
                    </div>
                    <div class="form-group col-md-2">
                        <?= $this->formLabel($form->get('genero')); ?>
                        <?= $this->formSelect($form->get('genero')); ?>
                        <ul class="text-danger"></ul>
                    </div>
                    <div class="form-group col-md-2">
                        <?= $this->formLabel($form->get('estado_civil')); ?>
                        <?= $this->formSelect($form->get('estado_civil')); ?>
                        <ul class="text-danger"></ul>
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <?= $this->formLabel($form->get('correo')); ?>
                        <?= $this->formText($form->get('correo')); ?>
                        <ul class="text-danger"></ul>
                    </div>
                    <div class="form-group col-md-6">
                        <?= $this->formLabel($form->get('telefono')); ?>
                        <?= $this->formText($form->get('telefono')); ?>
                        <ul class="text-danger"></ul>
                    </div>
                </div>
                <?= $this->formHidden($form->get('csrf')); ?>
                <ul class="text-danger"></ul>
                <?= $this->formText($form->get('input1')); ?>
      </div>
      <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
                <?= $this->formSubmit($form->get('btnGuardar')->setAttributes(['onClick' => 'guardar()'])); ?>
            <?= $this->form()->closeTag(); ?>
      </div>
    </div>
  </div>
</div>
<!-- [ modal ] fin -->