<?php
$title = $this->translate('Detalle');
$this->headMeta()->appendName('keywords', '');
$this->headMeta()->appendName('description', '');
$this->headTitle($this->escapeHtml($title));
$this->pageBreadcrumbs()->setItems([
    'Home' => $this->url('home'),
    'Contribuyentes' => $this->url('contribuyente'),
    'Detalle' => $this->url('contribuyente/ver'),
]);
?>
<!-- [ col ] start -->
<div class="col-md-6">
    <div class="card">
        <div class="card-header">
            <h5><?= $title ?></h5>
        </div>
        <div class="card-body">
            <table class="table table-striped table-bordered">
                <tbody>
                    <tr>
                        <td>Nombre</td>
                        <td><?= $contribuyente->getNombre() ?></td>
                    </tr>
                    <tr>
                        <td>Apellido Paterno</td>
                        <td><?= $contribuyente->getApellidoPaterno() ?></td>
                    </tr>
                    <tr>
                        <td>Apellido Materno</td>
                        <td><?= $contribuyente->getApellidoMaterno() ?></td>
                    </tr>
                    </tr>
                    <tr>
                        <td>R.F.C.</td>
                        <td><?= $contribuyente->getRfc() ?></td>
                    </tr>
                    </tr>
                    <tr>
                        <td>C.U.R.P.</td>
                        <td><?= $contribuyente->getCurp() ?></td>
                    </tr>
                </tbody>
            </table>
            <a href="<?= $this->url("contribuyente") ?>" class="btn btn-secondary"> Volver atrás</a>
        </div>
    </div>
</div>
<!-- [ col] end -->
<!-- [ col ] start -->
<div class="col-md-6">
    <div class="card">
        <div class="card-header">
            <h5><?= $title ?></h5>
        </div>
        <div class="card-body">
            <table class="table table-light">
                <thead class="thead-dark">
                    <tr>
                        <th>Tipo</th>
                        <th>Archivo</th>
                        <th>Fecha de subida</th>
                        <th>Acciones</th>
                    </tr>
                </thead>
                <tbody>
                    <?php if ($archivos): ?>
                        <?php foreach ($archivos as $archivo): ?>
                            <tr>
                                <td><?= $archivo->getIdArchivo()->getIdArchivoCategoria()->getNombre() ?></td>
                                <td><?= $archivo->getIdArchivo()->getUrl() ?></td>
                                <td><?= $archivo->getIdArchivo()->getCreatedAt()->format('Y-m-d h:m:s') ?></td>
                                <td>
                                    <a href="<?= $this->url('biblioteca/eliminar-archivo', ['action' => 'eliminar-archivo', 'predio' => $archivo->getIdContribuyente()->getIdContribuyente(), 'archivo' => $archivo->getIdArchivo()->getIdArchivo()]); ?>" class="btn btn-danger btn-sm"> Eliminar</a>
                                    <a href="<?= $this->url('biblioteca/imprimir-archivo', ['action' => 'imprimir-archivo', 'predio' => $archivo->getIdContribuyente()->getIdContribuyente(), 'archivo' => $archivo->getIdArchivo()->getIdArchivo()]); ?>" class="btn btn-success btn-sm"> Descargar</a>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    <?php else: ?>
                        <tr>
                            <td colspan="3" class="text-center">No hay archivos...</td>
                        </tr>
                    <?php endif; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>
<!-- [ col] end -->
