<?php
$title = $this->translate('Detalle');
$this->headMeta()->appendName('keywords', '');
$this->headMeta()->appendName('description', '');
$this->headTitle($this->escapeHtml($title));
$this->pageBreadcrumbs()->setItems([
    'Home' => $this->url('home'),
    'Contribuyentes' => $this->url('contribuyente'),
    'Detalle' => $this->url('contribuyente/ver'),
]);
// Css Requerido
$this->headLink()
    // Css FileInput
    ->prependStylesheet($this->basePath('js/plugins/FileInput/css/fileinput.min.css'))
    ;
// Js Requerido
$this ->inlineScript()
    // Js de la vista
    ->prependFile($this->basePath('js/catastro/contribuyente/view.js'))
    // Js FileInput
    ->prependFile($this->basePath('js/plugins/FileInput/js/locales/es.js'))
    ->prependFile($this->basePath('js/plugins/FileInput/js/fileinput.min.js'))
    ;
?>
<!-- [ col ] start -->
<div class="col-md-12">
    <div class="card">
        <div class="card-header">
            <h5><?= $title ?> Contribuyente</h5>
        </div>
        <div class="card-body">
            <table class="table table-striped table-bordered">
                <tbody>
                    <tr>
                        <td>Nombre</td>
                        <td><?= $contribuyente->getNombre() ?></td>
                    </tr>
                    <?php if ($contribuyente->getTipoPersona() == 'F'): ?>
                    <tr>
                        <td>Apellido Paterno</td>
                        <td><?= $contribuyente->getApellidoPaterno() ?></td>
                    </tr>
                    <tr>
                        <td>Apellido Materno</td>
                        <td><?= $contribuyente->getApellidoMaterno() ?></td>
                    </tr>
                    <?php endif; ?>
                    <tr>
                        <td>Razon Social</td>
                        <td><?= $contribuyente->getRazonSocial() ?></td>
                    </tr>
                    </tr>
                    <tr>
                        <td>R.F.C.</td>
                        <td><?= $contribuyente->getRfc() ?></td>
                    </tr>
                    </tr>
                    <?php if ($contribuyente->getTipoPersona() == 'F'): ?>
                    <tr>
                        <td>C.U.R.P.</td>
                        <td><?= $contribuyente->getCurp() ?></td>
                    </tr>
                    <tr>
                        <td>Genero</td>
                        <td>
                            <?php echo  $contribuyente->getGenero() == 'H' ? 'Hombre' : '' ?>
                            <?php echo  $contribuyente->getGenero() == 'M' ? 'Mujer' : '' ?>
                            <?php echo  $contribuyente->getGenero() == 'O' ? 'Otro' : '' ?>
                        </td>
                    </tr>
                    <?php endif; ?>
                    <tr>
                        <td>Correo Electrónico</td>
                        <td><?= $contribuyente->getCorreo() ?></td>
                    </tr>
                    <tr>
                        <td>Telefono</td>
                        <td><?= $contribuyente->getTelefono() ?></td>
                    </tr>
                    <tr>
                        <td>Fecha de Alta</td>
                        <td><?= $contribuyente->getCreatedAt()->format('Y-m-d h:m:s')  ?></td>
                    </tr>
                    <tr>
                        <td>Fecha Ultima Modificación</td>
                        <td><?= $contribuyente->getUpdatedAt()->format('Y-m-d h:m:s')  ?></td>
                    </tr>

                </tbody>
            </table>
            <a href="<?= $this->url("contribuyente") ?>" class="btn btn-secondary"> Volver atrás</a>
            <a href="<?= $this->url('contribuyente/editar', ['action' => 'editar', 'id' => $contribuyente->getIdContribuyente()]); ?>" class="btn btn-warning"> Editar datos</a>
        </div>
    </div>
</div>
<!-- [ col] end -->
<!-- [ col ] start -->
<div class="col-md-12">
    <div class="card">
        <div class="card-header">
            <h5>Archivos</h5>
            <div class="float-right">
                <button id="agregar-archivo" class="btn btn-success btn-sm" data-toggle="modal" data-target="#exampleModal">Agregar+</button>
            </div>
        </div>
        <div class="card-body">
            <table class="table table-light">
                <thead class="thead-dark">
                    <tr>
                        <th>Tipo</th>
                        <th>Archivo</th>
                        <th>Fecha de subida</th>
                        <th>Acciones</th>
                    </tr>
                </thead>
                <tbody>
                    <?php if ($archivos): ?>
                        <?php foreach ($archivos as $archivo): ?>
                            <tr>
                                <td><?= $archivo->getIdArchivo()->getIdArchivoCategoria()->getNombre() ?></td>
                                <td><?= $archivo->getIdArchivo()->getUrl() ?></td>
                                <td><?= $archivo->getIdArchivo()->getCreatedAt()->format('Y-m-d h:m:s') ?></td>
                                <td>
                                    <a target="_blank" href="<?= $this->url('biblioteca/ver-archivo', ['archivo'=>'file'], ['query'=>['name'=>$archivo->getIdArchivo()->getUrl()]]); ?>"  class="btn btn-info btn-sm" role="button"> Previsualizar</a>
                                    <a href="<?= $this->url('biblioteca/descargar-archivo', ['action' => 'descargar-archivo', 'archivo' => $archivo->getIdArchivo()->getIdArchivo()]); ?>" class="btn btn-success btn-sm"> Descargar</a>
                                    <a href="<?= $this->url('biblioteca/eliminar-archivo-contribuyente', ['action' => 'eliminar-archivo-contribuyente', 'contribuyente' => $archivo->getIdContribuyente()->getIdContribuyente(), 'archivo' => $archivo->getIdArchivo()->getIdArchivo()]); ?>" class="btn btn-danger btn-sm"> Eliminar</a>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    <?php else: ?>
                        <tr>
                            <td colspan="4" class="text-center">No hay archivos...</td>
                        </tr>
                    <?php endif; ?>
                </tbody>
            </table>

        </div>
    </div>
</div>
<!-- [ col] end -->
<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
    <div class="modal-content">
        <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Cargar archivo...</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        </div>
        <div class="modal-body">
            <form action="upload.php" method="post" enctype="multipart/form-data">
                <div class="form-group">
                    <input type="hidden" name="input1" value="<?= $contribuyenteId ?>">
                </div>
                <div class="form-group">
                    <select class="form-control" id="id_archivo_categoria" name="id_archivo_categoria">
                        <?php foreach($categorias as $categoria): ?>
                            <?= '<option value="'. $categoria->getIdArchivoCategoria() .'">' . $categoria->getNombre() . '</option>'?>
                        <?php endforeach;?>
                    </select>
                </div>
                <div class="form-group">
                    <div class="file-loading">
                        <input type="file" name="archivo" id="archivo">
                    </div>
                </div>
            </form>
        </div>
        <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
        </div>
    </div>
    </div>
</div>