<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<?= $this->doctype() ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('SIGOB')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/assets/images/favicon.ico'])
            ->prependStylesheet($this->basePath('assets/css/style.css'))
        ?>

        <!-- Scripts -->
        <?= $this->headScript() ?>
    </head>
    <body class="">
	<!-- [ Pre-loader ] start -->
	<div class="loader-bg">
		<div class="loader-track">
			<div class="loader-fill"></div>
		</div>
	</div>
	<!-- [ Pre-loader ] End -->

    <!-- [ navigation menu ] start -->
        <!-- Navigation bar -->
        <?php
        // Check if the activeMenuItemId passed to layout view model
        // and if so, use it for setting active navbar item.
        if (isset($activeMenuItemId)) {
            $this->mainMenu()->setActiveItemId($activeMenuItemId);
        }

        // Render the navbar
        echo $this->mainMenu()->render();
        ?>
	<!-- [ navigation menu ] end -->

    <!-- [ Header ] start -->
	<header class="navbar pcoded-header navbar-expand-lg headerpos-fixed header-blue">
        <div class="m-header">
            <a class="mobile-menu" id="mobile-collapse" href="#!"><span></span></a>
            <a href="#!" class="b-brand">
                <!-- ========   change your logo hear   ============ -->
                <img src=<?= $this->basePath('assets/images/logo.png') ?> alt="" class="logo">
                <img src=<?= $this->basePath('assets/images/logo-icon.png') ?> alt="" class="logo-thumb">
            </a>
            <a href="#!" class="mob-toggler">
                <i class="feather icon-more-vertical"></i>
            </a>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a href="#!" class="full-screen" onclick="javascript:toggleFullScreen()"><i class="feather icon-maximize"></i></a>
                </li>
            </ul>
            <ul class="navbar-nav ml-auto">
                <?php if (!$this->identity()): ?>
                    <li><a href="<?= $this->url('login') ?>">Login</a></li>
                <?php else: ?>
                    <li>
                        <div class="dropdown drp-user">
                            <a href="#!" class="dropdown-toggle" data-toggle="dropdown">
                                <img src=<?= $this->basePath('assets/images/user/avatar-1.png') ?> class="img-radius wid-40" alt="User-Profile-Image">
                            </a>
                            <div class="dropdown-menu dropdown-menu-right profile-notification">
                                <div class="pro-head">
                                    <img src=<?= $this->basePath('assets/images/user/avatar-1.png') ?> class="img-radius" alt="User-Profile-Image">
                                    <span>
                                        <?php
                                            if ($this->identity()) {
                                                echo ucfirst($this->identity());
                                            }
                                        ?>
                                    </span>
                                </div>
                                <ul class="pro-body">
                                    <li><a href="<?= $this->url('application', ['action'=>'settings'])?>" class="dropdown-item"><i class="feather icon-user"></i> Configuraciones</a></li>
                                    <li><a href="<?= $this->url('logout')?>" class="dropdown-item"><i class="feather icon-lock"></i> Salir</a></li>
                                </ul>
                            </div>
                        </div>
                    </li>
                <?php endif; ?>
            </ul>
        </div>
	</header>
    <!-- [ Header ] end -->

    <!-- [ Main Content ] start -->
    <div class="pcoded-main-container">
        <div class="pcoded-content">
            <!-- [ breadcrumb ] start -->
            <div class="page-header">
                <div class="page-block">
                    <div class="row align-items-center">
                        <div class="col-md-12">
                            <div class="page-header-title">
                                <h5 class="m-b-10">SIGOB</h5>
                            </div>
                            <?= $this->pageBreadcrumbs()->render(); ?>
                        </div>
                    </div>
                </div>
            </div>
            <!-- [ breadcrumb ] end -->
            <?=$this->partial('partials/flashMessenger', $this->flashMessenger())?>
            <!-- [ Main Content ] start -->
            <div class="row">
                <!-- [ sample-page ] start -->
                    <?= $this->content ?>
                <!-- [ sample-page ] end -->
            </div>
            <!-- [ Main Content ] end -->
        </div>
    </div>
    <!-- [ Main Content ] end -->
    <!-- Required Js -->
    <?= $this->inlineScript()
        ->prependFile($this->basePath('js/app.js'))
        ->prependFile($this->basePath('assets/js/menu-setting.min.js'))
        ->prependFile($this->basePath('assets/js/pcoded.min.js'))
        ->prependFile($this->basePath('assets/js/plugins/bootstrap.min.js'))
        ->prependFile($this->basePath('assets/js/vendor-all.min.js'))
    ?>
</body>
</html>
