<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<?= $this->headTitle('SIGOB')->setSeparator(' - ')->setAutoEscape(false) ?>

	<?= $this->headMeta()
		->appendName('viewport', 'width=device-width, initial-scale=1.0')
		->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
	?>

	<!-- Le styles -->
	<?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/assets/images/favicon.ico'])
		->prependStylesheet($this->basePath('assets/css/style.css'))
	?>

	<!-- Scripts -->
	<?= $this->headScript() ?>
</head>
<!-- [ signin-img ] start -->
<div class="auth-wrapper align-items-stretch aut-bg-img">
	<div class="flex-grow-1">
		<div class="h-100 d-md-flex align-items-center auth-side-img">
			<div class="col-sm-10 auth-content w-auto">
				<img src="assets/images/auth/auth-logo.png" alt="" class="img-fluid">
				<h1 class="text-white my-4">Welcome Back!</h1>
				<h4 class="text-white font-weight-normal">Signin to your account and get explore the Gradient able Dashboard Template.<br/>Do not forget to play with live customizer</h4>
			</div>
		</div>
		<?= $this->content ?>
	</div>
</div>
<!-- [ signin-img ] end -->

<!-- Required Js -->
<?= $this->inlineScript()
	->prependFile($this->basePath('assets/js/waves.min.js'))
	->prependFile($this->basePath('assets/js/plugins/bootstrap.min.js'))
	->prependFile($this->basePath('assets/js/vendor-all.min.js'))
?>
</body>
</html>
