<?php
$title = $this->translate('Roles');

$this->headMeta()->appendName('keywords', '');

$this->headMeta()->appendName('description', '');

$this->headTitle($this->escapeHtml($title));

$this->mainMenu()->setActiveItemId('roles');

$this->pageBreadcrumbs()->setItems([
    'Home'=>$this->url('home'),
    'Manage Roles'=>$this->url('roles'),
]);
?>
<!-- [ col ] start -->
<div class="col-md-12">
    <div class="card">
        <div class="card-header">
            <h1>Manage Roles</h1>
        </div>
        <div class="card-body">
            <div class="row">
                <div class="col-md-1 col-xs-12 mb-4" align=center>
                    <a class="btn btn-primary" href="<?= $this->url('roles', ['action'=>'add']); ?>"> New Role</a>
                </div>
            </div>
            <table class="table table-light">
                <thead class="thead-light">
                    <tr>
                        <th>ID</th>
                        <th>Name</th>
                        <th>Description</th>
                        <th>Date Created</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($roles as $role): ?>
                        <tr>
                            <td><?= $this->escapeHtml($role->getId()); ?></td>
                            <td>
                                <a href="<?= $this->url('roles', ['action'=>'view', 'id'=>$role->getId()]); ?>">
                                    <?= $this->escapeHtml($role->getName()); ?>
                                </a>
                            </td>
                            <td>
                                <?= $this->escapeHtml($role->getDescription()); ?></a>
                            </td>
                            <td><nobr><?= $this->escapeHtml($role->getDateCreated()); ?></nobr></td>
                            <td>
                                <nobr>
                                    <a class="btn btn-info" href="<?= $this->url('roles', ['action'=>'edit', 'id'=>$role->getId()]); ?>">Edit</a>
                                    <a class="btn btn-danger" href="<?= $this->url('roles',['action'=>'delete', 'id'=>$role->getId()]); ?>"> Delete</a>
                                </nobr>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>
<!-- [ col] end -->
