<?php
$title = $this->translate('View Role');

$this->headMeta()->appendName('keywords', '');

$this->headMeta()->appendName('description', '');

$this->headTitle($this->escapeHtml($title));

$this->mainMenu()->setActiveItemId('roles');

$this->pageBreadcrumbs()->setItems([
    'Home'=>$this->url('home'),
    'Manage Roles'=>$this->url('roles'),
    'View Role ' . $role->getName() => $this->url('roles', ['action'=>'view', 'id'=>$role->getId()])
]);
?>
<!-- [ col ] start -->
<div class="col-md-6">
    <div class="card">
        <div class="card-body">
            <h1>View Role <?= $this->escapeHtml($role->getName()) ?></h1>
            <table class="table table-striped table-bordered">
                <tr>
                    <th>ID:</th>
                    <td><?= $this->escapeHtml($role->getId()) ?></th>
                </tr>
                <tr>
                    <th>Name:</th>
                    <td><?= $this->escapeHtml($role->getName()) ?></th>
                </tr>
                <tr>
                    <th>Description:</th>
                    <td><?= $this->escapeHtml($role->getDescription()) ?></th>
                </tr>
                <tr>
                    <th>Date Created:</th>
                    <td><?= $this->escapeHtml($role->getDateCreated()) ?></th>
                </tr>
            </table>
            <div>
                <a class="btn btn-secondary" href="<?= $this->url('roles', ['action'=>'edit', 'id'=>$role->getId()]); ?>"> Edit Role</a>
            </div>
        </div>
    </div>
</div>
<!-- [ col] end -->

<div class="col-md-6">
    <div class="card">
        <div class="card-body">
            <h2>Permissions</h2>
            <table class="table table-striped table-bordered">
                <tr>
                    <th>Name</th>
                    <th>Description</th>
                </tr>
                <?php foreach($allPermissions as $permission): ?>
                <tr>
                    <td>
                        <input type="checkbox" disabled <?php if (isset($effectivePermissions[$permission->getName()])) echo 'checked'; ?>>
                        <?= $this->escapeHtml($permission->getName()) ?>
                        <?php if (isset($effectivePermissions[$permission->getName()]) && $effectivePermissions[$permission->getName()]=='inherited'): ?>
                        <em>(inherited)</em>
                        <?php endif; ?>
                    </td>
                    <td><?= $this->escapeHtml($permission->getDescription()) ?></td>
                </tr>
                <?php endforeach; ?>
            </table>
            <div>
                <a class="btn btn-secondary" href="<?= $this->url('roles', ['action'=>'editPermissions', 'id'=>$role->getId()]) ?>"> Edit Permissions</a>
            </div>
        </div>
    </div>
</div>
<!-- [ col] end -->
