<?php
$title = $this->translate('View Permission');

$this->headMeta()->appendName('keywords', '');

$this->headMeta()->appendName('description', '');

$this->headTitle($this->escapeHtml($title));

$this->mainMenu()->setActiveItemId('permissions');

$this->pageBreadcrumbs()->setItems([
    'Home'=>$this->url('home'),
    'Manage Permissions'=>$this->url('permissions'),
    'View Permission'=>$this->url('permissions', ['action'=>'view', 'id'=>$permission->getId()])
]);
?>
<!-- [ col ] start -->
<div class="col-md-6">
    <div class="card">
        <div class="card-header">
            <h5><?= $title ?></h5>
        </div>
        <div class="card-body">
            <table class="table table-striped table-bordered">
                <tr>
                    <th>ID:</th>
                    <td><?= $this->escapeHtml($permission->getId()) ?></th>
                </tr>
                <tr>
                    <th>Name:</th>
                    <td><?= $this->escapeHtml($permission->getName()) ?></th>
                </tr>
                <tr>
                    <th>Description:</th>
                    <td><?= $this->escapeHtml($permission->getDescription()) ?></th>
                </tr>
                <tr>
                    <th>Date Created:</th>
                    <td><?= $this->escapeHtml($permission->getDateCreated()) ?></th>
                </tr>
            </table>
        </div>
    </div>
</div>
<!-- [ col] end -->
