<?php
$title = $this->translate('Detalle');
$this->headMeta()->appendName('keywords', '');
$this->headMeta()->appendName('description', '');
$this->headTitle($this->escapeHtml($title));
$this->pageBreadcrumbs()->setItems([
    'Home' => $this->url('home'),
    'Categorias' => $this->url('categoria'),
    'Detalle' => $this->url('categoria/ver'),
]);
?>
<!-- [ col ] start -->
<div class="col-md-6">
    <div class="card">
        <div class="card-header">
            <h5><?= $title ?></h5>
        </div>
        <div class="card-body">
            <table class="table table-striped table-bordered">
                <tbody>
                    <tr>
                        <td>Nombre</td>
                        <td><?= $categoria->getNombre() ?></td>
                    </tr>
                </tbody>
            </table>
            <a href="<?= $this->url("categoria") ?>" class="btn btn-secondary"> Volver atrás</a>
        </div>
    </div>
</div>
<!-- [ col] end -->
